#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

def build(bld):
    bld.objects(
        target = 'modules',
        source = 'scireg.cpp',
        includes = '. ..',
        use = 'SYSTEMC',
        install_path = None
    )

    bld.install_files(os.path.join(bld.env.PREFIX, 'include', 'modules'), 'abi_if.hpp instruction.hpp sparse_memory_at.hpp sparse_memory_lt.hpp memory_lt.hpp memory_at.hpp pin_target.hpp scireg.h')
