/***************************************************************************//**
*
*           _/       _/_/_/      _/         _/
*         _/_/      _/    _/    _/_/      __/
*       _/  _/     _/    _/    _/ _/    _/_/
*     _/_/_/_/    _/_/_/      _/  _/  _/ _/
*   _/      _/   _/    _/    _/   _/_/  _/
* _/        _/  _/      _/  _/    _/   _/
*
* @brief    This file is part of the SoCRocket ARM ISS generated by TRAP.
* @details  This SystemC model was automatically generated by running
*           $ python ARMArch.py
*           Please refer to the ARM TRAP source files for documentation.
* @author   Lillian Tadros (Technische Universitaet Dortmund)
* @date     2015-2016 Technische Universitaet Dortmund
*
*
* (c) 2014-2016
* Technische Universitaet Dortmund
* Institut fuer Roboterforschung
* Project Embedded Multi-Core Systems for Mixed Criticality
* Applications in Dynamic and Changeable Real-time Environments (EMC2)
*
*
* This file is part of ARMCortexA9.
*
* ARMCortexA9 is free software; you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation; either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
* or see <http://www.gnu.org/licenses/>.
*
*******************************************************************************/

#include "decoder.hpp"
#include "instructions.hpp"



using namespace core_armcortexa9_funclt;

core_armcortexa9_funclt::CacheElem::CacheElem(
    Instruction* instr,
    unsigned count) :
  instr(instr),
  count(count) {


} // CacheElem()

// -----------------------------------------------------------------------------

core_armcortexa9_funclt::CacheElem::CacheElem() :
  instr(NULL),
  count(1) {


} // CacheElem()

// -----------------------------------------------------------------------------


// *****************************************************************************

int core_armcortexa9_funclt::Decoder::decode(unsigned instr_code) const throw()
{

  switch(instr_code & 0xe000000U) {
    case 0x0U: {
      switch(instr_code & 0x3000000U) {
        case 0x1000000U: {
          switch(instr_code & 0xc00000U) {
            case 0x800000U: {
              switch(instr_code & 0x30U) {
                case 0x10U: {
                  switch(instr_code & 0xc0U) {
                    case 0x40U: {
                      if ((instr_code & 0x200000U) == 0x0) {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction ORR_sr
                          return 45;
                        }
                      }
                      else {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction ASR_sr
                          return 53;
                        }
                      }
                    break;}
                    case 0x0U: {
                      if ((instr_code & 0x200000U) != 0x0) {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction LSL_sr
                          return 57;
                        }
                      }
                      else {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction ORR_sr
                          return 45;
                        }
                      }
                    break;}
                    case 0x80U: {
                      if ((instr_code & 0x100000U) != 0x0) {
                        if ((instr_code & 0x200000U) == 0x0) {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction LDREX
                            return 80;
                          }
                        }
                        else {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction LDREXD
                            return 93;
                          }
                        }
                      }
                      else {
                        if ((instr_code & 0x200000U) != 0x0) {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction STREXD
                            return 105;
                          }
                        }
                        else {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction STREX
                            return 96;
                          }
                        }
                      }
                    break;}
                    case 0xc0U: {
                      if ((instr_code & 0x100000U) == 0x0) {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction LDRD_r
                          return 92;
                        }
                      }
                      else {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction LDRSB_r
                          return 85;
                        }
                      }
                    break;}
                    default: {
                      // Invalid pattern
                      return 161;
                    }
                  }
                break;}
                case 0x30U: {
                  if ((instr_code & 0x200080U) != 0x0) {
                    if ((instr_code & 0x80U) == 0x0) {
                      if ((instr_code & 0x40U) == 0x0) {
                        if (((instr_code & 0x200000U) == 0x200000) && ((instr_code
                        & 0xf0000000U) != 0xf0000000)) {
                          // Instruction LSR_sr
                          return 55;
                        }
                      }
                      else {
                        if (((instr_code & 0x200000U) == 0x200000) && ((instr_code
                        & 0xf0000000U) != 0xf0000000)) {
                          // Instruction ROR_sr
                          return 59;
                        }
                      }
                    }
                    else {
                      if ((instr_code & 0x40U) != 0x40) {
                        if ((instr_code & 0x100000U) != 0x0) {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction LDRH_r
                            return 87;
                          }
                        }
                        else {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction STRH_r
                            return 101;
                          }
                        }
                      }
                      else {
                        if ((instr_code & 0x100000U) != 0x0) {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction LDRSH_r
                            return 90;
                          }
                        }
                        else {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction STRD_r
                            return 104;
                          }
                        }
                      }
                    }
                  }
                  else {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction ORR_sr
                      return 45;
                    }
                  }
                break;}
                case 0x0U: {
                  if ((instr_code & 0x200040U) == 0x200000) {
                    if ((instr_code & 0xf80U) == 0x0) {
                      if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code
                      & 0x10f000U) != 0x10f000)) {
                        // Instruction MOV_r
                        return 119;
                      }
                    }
                    else {
                      if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code
                      & 0x1f0000U) != 0x1f0000) && ((instr_code & 0xf80U) !=
                      0x0)) {
                        // Instruction LSL_r
                        return 56;
                      }
                    }
                  }
                  else {
                    if ((instr_code & 0x200000U) != 0x0) {
                      if (((instr_code & 0x40U) == 0x40) && ((instr_code &
                      0xf0000000U) != 0xf0000000) && ((instr_code & 0x1f0000U)
                      != 0x1f0000)) {
                        // Instruction ASR_r
                        return 52;
                      }
                    }
                    else {
                      if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code
                      & 0x10f000U) != 0x10f000)) {
                        // Instruction ORR_r
                        return 44;
                      }
                    }
                  }
                break;}
                case 0x20U: {
                  if ((instr_code & 0x200000U) != 0x0) {
                    if ((instr_code & 0x40U) != 0x0) {
                      if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code
                      & 0x1f0000U) != 0x1f0000)) {
                        // Instruction ROR_r
                        return 58;
                      }
                    }
                    else {
                      if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code
                      & 0x1f0000U) != 0x1f0000)) {
                        // Instruction LSR_r
                        return 54;
                      }
                    }
                  }
                  else {
                    if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code
                    & 0x10f000U) != 0x10f000)) {
                      // Instruction ORR_r
                      return 44;
                    }
                  }
                break;}
                default: {
                  // Invalid pattern
                  return 161;
                }
              }
            break;}
            case 0x400000U: {
              switch(instr_code & 0x30U) {
                case 0x30U: {
                  if ((instr_code & 0x100080U) != 0x0) {
                    if ((instr_code & 0x80U) != 0x0) {
                      if ((instr_code & 0x40U) == 0x0) {
                        if ((instr_code & 0x100000U) == 0x0) {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction STRH_i
                            return 100;
                          }
                        }
                        else {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction LDRH_i
                            return 86;
                          }
                        }
                      }
                      else {
                        if ((instr_code & 0x100000U) == 0x0) {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction STRD
                            return 103;
                          }
                        }
                        else {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction LDRSH_i
                            return 89;
                          }
                        }
                      }
                    }
                    else {
                      if ((instr_code & 0x200000U) == 0x0) {
                        if (((instr_code & 0x100000U) == 0x100000) && ((instr_code
                        & 0xf0000000U) != 0xf0000000)) {
                          // Instruction CMP_sr
                          return 77;
                        }
                      }
                      else {
                        if (((instr_code & 0x100000U) == 0x100000) && ((instr_code
                        & 0xf0000000U) != 0xf0000000)) {
                          // Instruction CMN_sr
                          return 74;
                        }
                      }
                    }
                  }
                  else {
                    if (((instr_code & 0x200040U) == 0x200040) && ((instr_code &
                    0xf0000000U) != 0xf0000000)) {
                      // Instruction SMC
                      return 153;
                    }
                  }
                break;}
                case 0x10U: {
                  if ((instr_code & 0x100000U) != 0x0) {
                    if ((instr_code & 0x200080U) == 0x0) {
                      if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                        // Instruction CMP_sr
                        return 77;
                      }
                    }
                    else {
                      if ((instr_code & 0x80U) == 0x0) {
                        if (((instr_code & 0x200000U) == 0x200000) && ((instr_code
                        & 0xf0000000U) != 0xf0000000)) {
                          // Instruction CMN_sr
                          return 74;
                        }
                      }
                      else {
                        if (((instr_code & 0x40U) == 0x40) && ((instr_code &
                        0xf0000000U) != 0xf0000000)) {
                          // Instruction LDRSB_i
                          return 84;
                        }
                      }
                    }
                  }
                  else {
                    if ((instr_code & 0x40U) != 0x0) {
                      if ((instr_code & 0x80U) != 0x0) {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction LDRD_i
                          return 91;
                        }
                      }
                      else {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction QDADDSUB
                          return 26;
                        }
                      }
                    }
                    else {
                      if ((instr_code & 0x80U) == 0x0) {
                        if (((instr_code & 0x200000U) == 0x200000) && ((instr_code
                        & 0xf0000000U) != 0xf0000000)) {
                          // Instruction CLZ
                          return 64;
                        }
                      }
                      else {
                        if (((instr_code & 0x200000U) == 0x0) && ((instr_code &
                        0xf0000000U) != 0xf0000000)) {
                          // Instruction SWP
                          return 122;
                        }
                      }
                    }
                  }
                break;}
                case 0x0U: {
                  if ((instr_code & 0x100000U) != 0x0) {
                    if ((instr_code & 0x200000U) == 0x0) {
                      if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                        // Instruction CMP_r
                        return 76;
                      }
                    }
                    else {
                      if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                        // Instruction CMN_r
                        return 73;
                      }
                    }
                  }
                  else {
                    if ((instr_code & 0x80U) != 0x80) {
                      if ((instr_code & 0x200000U) == 0x0) {
                        if (((instr_code & 0x40U) == 0x0) && ((instr_code &
                        0xf0000000U) != 0xf0000000)) {
                          // Instruction MRS
                          return 123;
                        }
                      }
                      else {
                        if (((instr_code & 0x40U) == 0x0) && ((instr_code &
                        0xf0000000U) != 0xf0000000)) {
                          // Instruction MSR_r
                          return 125;
                        }
                      }
                    }
                    else {
                      if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                        // Instruction SMULBW
                        return 31;
                      }
                    }
                  }
                break;}
                case 0x20U: {
                  if ((instr_code & 0x100000U) != 0x0) {
                    if ((instr_code & 0x200000U) == 0x0) {
                      if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                        // Instruction CMP_r
                        return 76;
                      }
                    }
                    else {
                      if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                        // Instruction CMN_r
                        return 73;
                      }
                    }
                  }
                  else {
                    if (((instr_code & 0x80U) == 0x80) && ((instr_code & 0xf0000000U)
                    != 0xf0000000)) {
                      // Instruction SMULBW
                      return 31;
                    }
                  }
                break;}
                default: {
                  // Invalid pattern
                  return 161;
                }
              }
            break;}
            case 0x0U: {
              switch(instr_code & 0x30U) {
                case 0x10U: {
                  if ((instr_code & 0xf0000000U) != 0xf0000000) {
                    if ((instr_code & 0x80U) == 0x0) {
                      if ((instr_code & 0x100000U) != 0x0) {
                        if ((instr_code & 0x200000U) != 0x0) {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction TEQ_sr
                            return 48;
                          }
                        }
                        else {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction TST_sr
                            return 51;
                          }
                        }
                      }
                      else {
                        if ((instr_code & 0x40U) == 0x0) {
                          if (((instr_code & 0x200000U) == 0x200000) && ((instr_code
                          & 0xf0000000U) != 0xf0000000)) {
                            // Instruction BX
                            return 128;
                          }
                        }
                        else {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction QDADDSUB
                            return 26;
                          }
                        }
                      }
                    }
                    else {
                      if ((instr_code & 0x40U) != 0x0) {
                        if ((instr_code & 0x100000U) == 0x0) {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction LDRD_r
                            return 92;
                          }
                        }
                        else {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction LDRSB_r
                            return 85;
                          }
                        }
                      }
                      else {
                        if (((instr_code & 0x300000U) == 0x0) && ((instr_code &
                        0xf0000000U) != 0xf0000000)) {
                          // Instruction SWP
                          return 122;
                        }
                      }
                    }
                  }
                  else {
                    if (((instr_code & 0x310000U) == 0x0)) {
                      // Instruction CPS
                      return 134;
                    }
                  }
                break;}
                case 0x30U: {
                  if ((instr_code & 0x100000U) == 0x100000) {
                    if ((instr_code & 0x80U) == 0x0) {
                      if ((instr_code & 0x200000U) != 0x0) {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction TEQ_sr
                          return 48;
                        }
                      }
                      else {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction TST_sr
                          return 51;
                        }
                      }
                    }
                    else {
                      if ((instr_code & 0x40U) == 0x0) {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction LDRH_r
                          return 87;
                        }
                      }
                      else {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction LDRSH_r
                          return 90;
                        }
                      }
                    }
                  }
                  else {
                    if ((instr_code & 0x40U) == 0x0) {
                      if ((instr_code & 0x80U) == 0x0) {
                        if (((instr_code & 0x200000U) == 0x200000) && ((instr_code
                        & 0xf0000000U) != 0xf0000000)) {
                          // Instruction BLX_r
                          return 130;
                        }
                      }
                      else {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction STRH_r
                          return 101;
                        }
                      }
                    }
                    else {
                      if ((instr_code & 0x80U) != 0x0) {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction STRD_r
                          return 104;
                        }
                      }
                      else {
                        if (((instr_code & 0x200000U) == 0x200000) && ((instr_code
                        & 0xf0000000U) != 0xf0000000)) {
                          // Instruction BKPT
                          return 132;
                        }
                      }
                    }
                  }
                break;}
                case 0x0U: {
                  if ((instr_code & 0x100000U) == 0x0) {
                    if ((instr_code & 0xf0000000U) != 0xf0000000) {
                      if ((instr_code & 0x80U) != 0x80) {
                        if ((instr_code & 0x200000U) == 0x0) {
                          if (((instr_code & 0x40U) == 0x0) && ((instr_code &
                          0xf0000000U) != 0xf0000000)) {
                            // Instruction MRS
                            return 123;
                          }
                        }
                        else {
                          if (((instr_code & 0x40U) == 0x0) && ((instr_code &
                          0xf0000000U) != 0xf0000000)) {
                            // Instruction MSR_r
                            return 125;
                          }
                        }
                      }
                      else {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction SMULBW
                          return 31;
                        }
                      }
                    }
                    else {
                      if ((instr_code & 0x10000U) == 0x0) {
                        if (((instr_code & 0x200000U) == 0x0)) {
                          // Instruction CPS
                          return 134;
                        }
                      }
                      else {
                        if (((instr_code & 0x2000c0U) == 0x0)) {
                          // Instruction SETEND
                          return 145;
                        }
                      }
                    }
                  }
                  else {
                    if ((instr_code & 0x200000U) != 0x0) {
                      if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                        // Instruction TEQ_r
                        return 47;
                      }
                    }
                    else {
                      if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                        // Instruction TST_r
                        return 50;
                      }
                    }
                  }
                break;}
                case 0x20U: {
                  if ((instr_code & 0x100000U) != 0x0) {
                    if ((instr_code & 0x200000U) != 0x0) {
                      if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                        // Instruction TEQ_r
                        return 47;
                      }
                    }
                    else {
                      if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                        // Instruction TST_r
                        return 50;
                      }
                    }
                  }
                  else {
                    if ((instr_code & 0x80U) != 0x0) {
                      if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                        // Instruction SMULBW
                        return 31;
                      }
                    }
                    else {
                      if (((instr_code & 0x200040U) == 0x200000) && ((instr_code
                      & 0xf0000000U) != 0xf0000000)) {
                        // Instruction BXJ
                        return 131;
                      }
                    }
                  }
                break;}
                default: {
                  // Invalid pattern
                  return 161;
                }
              }
            break;}
            case 0xc00000U: {
              switch(instr_code & 0x30U) {
                case 0x30U: {
                  if ((instr_code & 0x80U) != 0x0) {
                    if ((instr_code & 0x40U) == 0x0) {
                      if ((instr_code & 0x100000U) == 0x0) {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction STRH_i
                          return 100;
                        }
                      }
                      else {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction LDRH_i
                          return 86;
                        }
                      }
                    }
                    else {
                      if ((instr_code & 0x100000U) == 0x0) {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction STRD
                          return 103;
                        }
                      }
                      else {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction LDRSH_i
                          return 89;
                        }
                      }
                    }
                  }
                  else {
                    if ((instr_code & 0x200000U) != 0x0) {
                      if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                        // Instruction MVN_sr
                        return 42;
                      }
                    }
                    else {
                      if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                        // Instruction BIC_sr
                        return 63;
                      }
                    }
                  }
                break;}
                case 0x10U: {
                  if ((instr_code & 0x200080U) != 0x200000) {
                    if ((instr_code & 0x80U) != 0x0) {
                      if ((instr_code & 0x40U) == 0x0) {
                        if ((instr_code & 0x100000U) != 0x0) {
                          if ((instr_code & 0x200000U) == 0x0) {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction LDREXB
                              return 83;
                            }
                          }
                          else {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction LDREXH
                              return 88;
                            }
                          }
                        }
                        else {
                          if ((instr_code & 0x200000U) == 0x0) {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction STREXB
                              return 99;
                            }
                          }
                          else {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction STREXH
                              return 102;
                            }
                          }
                        }
                      }
                      else {
                        if ((instr_code & 0x100000U) == 0x0) {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction LDRD_i
                            return 91;
                          }
                        }
                        else {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction LDRSB_i
                            return 84;
                          }
                        }
                      }
                    }
                    else {
                      if (((instr_code & 0x200000U) == 0x0) && ((instr_code &
                      0xf0000000U) != 0xf0000000)) {
                        // Instruction BIC_sr
                        return 63;
                      }
                    }
                  }
                  else {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction MVN_sr
                      return 42;
                    }
                  }
                break;}
                case 0x0U: {
                  if ((instr_code & 0x200000U) != 0x0) {
                    if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code
                    & 0x10f000U) != 0x10f000)) {
                      // Instruction MVN_r
                      return 41;
                    }
                  }
                  else {
                    if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code
                    & 0x10f000U) != 0x10f000)) {
                      // Instruction BIC_r
                      return 62;
                    }
                  }
                break;}
                case 0x20U: {
                  if ((instr_code & 0x200000U) != 0x0) {
                    if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code
                    & 0x10f000U) != 0x10f000)) {
                      // Instruction MVN_r
                      return 41;
                    }
                  }
                  else {
                    if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code
                    & 0x10f000U) != 0x10f000)) {
                      // Instruction BIC_r
                      return 62;
                    }
                  }
                break;}
                default: {
                  // Invalid pattern
                  return 161;
                }
              }
            break;}
            default: {
              // Invalid pattern
              return 161;
            }
          }
        break;}
        case 0x0U: {
          switch(instr_code & 0xc00000U) {
            case 0x400000U: {
              if ((instr_code & 0x200010U) != 0x0) {
                if ((instr_code & 0x10U) != 0x0) {
                  if ((instr_code & 0x200080U) != 0x0) {
                    if ((instr_code & 0x80U) != 0x0) {
                      switch(instr_code & 0x60U) {
                        case 0x20U: {
                          if ((instr_code & 0x100000U) == 0x0) {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction STRH_i
                              return 100;
                            }
                          }
                          else {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction LDRH_i
                              return 86;
                            }
                          }
                        break;}
                        case 0x60U: {
                          if ((instr_code & 0x100000U) == 0x0) {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction STRD
                              return 103;
                            }
                          }
                          else {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction LDRSH_i
                              return 89;
                            }
                          }
                        break;}
                        case 0x40U: {
                          if ((instr_code & 0x100000U) == 0x0) {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction LDRD_i
                              return 91;
                            }
                          }
                          else {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction LDRSB_i
                              return 84;
                            }
                          }
                        break;}
                        case 0x0U: {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            if (((instr_code & 0xff000f0U) == 0x400090) &&
                            ((instr_code & 0xf0000000U) != 0xf0000000U)) {
                              // Instruction UMAAL
                              return 30;
                            }
                            if ((instr_code & 0xf8000f0U) == 0x90U) {
                              // Instruction MUL
                              return 27;
                            }
                          }
                        break;}
                        default: {
                          // Invalid pattern
                          return 161;
                        }
                      }
                    }
                    else {
                      if (((instr_code & 0x200000U) == 0x200000) && ((instr_code
                      & 0xf0000000U) != 0xf0000000)) {
                        // Instruction RSB_sr
                        return 14;
                      }
                    }
                  }
                  else {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction SUB_sr
                      return 8;
                    }
                  }
                }
                else {
                  if (((instr_code & 0x200000U) == 0x200000) && ((instr_code &
                  0xf0000000U) != 0xf0000000) && ((instr_code & 0x10f000U) !=
                  0x10f000)) {
                    // Instruction RSB_r
                    return 13;
                  }
                }
              }
              else {
                if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
                0x10f000U) != 0x10f000)) {
                  // Instruction SUB_r
                  return 7;
                }
              }
            break;}
            case 0x800000U: {
              if ((instr_code & 0x200010U) != 0x0) {
                if ((instr_code & 0x10U) != 0x0) {
                  switch(instr_code & 0xc0U) {
                    case 0x40U: {
                      if ((instr_code & 0x200000U) == 0x0) {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction ADD_sr
                          return 2;
                        }
                      }
                      else {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction ADC_sr
                          return 5;
                        }
                      }
                    break;}
                    case 0x0U: {
                      if ((instr_code & 0x200000U) == 0x0) {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction ADD_sr
                          return 2;
                        }
                      }
                      else {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction ADC_sr
                          return 5;
                        }
                      }
                    break;}
                    case 0xc0U: {
                      if ((instr_code & 0x20U) != 0x20) {
                        if ((instr_code & 0x100000U) == 0x0) {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction LDRD_r
                            return 92;
                          }
                        }
                        else {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction LDRSB_r
                            return 85;
                          }
                        }
                      }
                      else {
                        if ((instr_code & 0x100000U) != 0x0) {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction LDRSH_r
                            return 90;
                          }
                        }
                        else {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction STRD_r
                            return 104;
                          }
                        }
                      }
                    break;}
                    case 0x80U: {
                      if ((instr_code & 0x20U) == 0x20) {
                        if ((instr_code & 0x100000U) != 0x0) {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction LDRH_r
                            return 87;
                          }
                        }
                        else {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction STRH_r
                            return 101;
                          }
                        }
                      }
                      else {
                        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                          // Instruction MULL
                          return 29;
                        }
                      }
                    break;}
                    default: {
                      // Invalid pattern
                      return 161;
                    }
                  }
                }
                else {
                  if (((instr_code & 0x200000U) == 0x200000) && ((instr_code &
                  0xf0000000U) != 0xf0000000) && ((instr_code & 0x10f000U) !=
                  0x10f000)) {
                    // Instruction ADC_r
                    return 4;
                  }
                }
              }
              else {
                if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
                0x10f000U) != 0x10f000)) {
                  // Instruction ADD_r
                  return 1;
                }
              }
            break;}
            case 0x0U: {
              if ((instr_code & 0x200010U) != 0x0) {
                if ((instr_code & 0x10U) != 0x0) {
                  if ((instr_code & 0x200080U) != 0x0) {
                    if ((instr_code & 0x80U) != 0x0) {
                      switch(instr_code & 0x60U) {
                        case 0x40U: {
                          if ((instr_code & 0x100000U) == 0x0) {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction LDRD_r
                              return 92;
                            }
                          }
                          else {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction LDRSB_r
                              return 85;
                            }
                          }
                        break;}
                        case 0x20U: {
                          if ((instr_code & 0x100000U) != 0x0) {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction LDRH_r
                              return 87;
                            }
                          }
                          else {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction STRH_r
                              return 101;
                            }
                          }
                        break;}
                        case 0x0U: {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            if (((instr_code & 0xff000f0U) == 0x400090) &&
                            ((instr_code & 0xf0000000U) != 0xf0000000U)) {
                              // Instruction UMAAL
                              return 30;
                            }
                            if ((instr_code & 0xf8000f0U) == 0x90U) {
                              // Instruction MUL
                              return 27;
                            }
                          }
                        break;}
                        case 0x60U: {
                          if ((instr_code & 0x100000U) != 0x0) {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction LDRSH_r
                              return 90;
                            }
                          }
                          else {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction STRD_r
                              return 104;
                            }
                          }
                        break;}
                        default: {
                          // Invalid pattern
                          return 161;
                        }
                      }
                    }
                    else {
                      if (((instr_code & 0x200000U) == 0x200000) && ((instr_code
                      & 0xf0000000U) != 0xf0000000)) {
                        // Instruction EOR_sr
                        return 39;
                      }
                    }
                  }
                  else {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction AND_sr
                      return 36;
                    }
                  }
                }
                else {
                  if (((instr_code & 0x200000U) == 0x200000) && ((instr_code &
                  0xf0000000U) != 0xf0000000) && ((instr_code & 0x10f000U) !=
                  0x10f000)) {
                    // Instruction EOR_r
                    return 38;
                  }
                }
              }
              else {
                if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
                0x10f000U) != 0x10f000)) {
                  // Instruction AND_r
                  return 35;
                }
              }
            break;}
            case 0xc00000U: {
              if ((instr_code & 0x200010U) != 0x0) {
                if ((instr_code & 0x10U) != 0x0) {
                  if ((instr_code & 0x200080U) != 0x0) {
                    if ((instr_code & 0x80U) != 0x0) {
                      switch(instr_code & 0x60U) {
                        case 0x20U: {
                          if ((instr_code & 0x100000U) == 0x0) {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction STRH_i
                              return 100;
                            }
                          }
                          else {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction LDRH_i
                              return 86;
                            }
                          }
                        break;}
                        case 0x60U: {
                          if ((instr_code & 0x100000U) == 0x0) {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction STRD
                              return 103;
                            }
                          }
                          else {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction LDRSH_i
                              return 89;
                            }
                          }
                        break;}
                        case 0x40U: {
                          if ((instr_code & 0x100000U) == 0x0) {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction LDRD_i
                              return 91;
                            }
                          }
                          else {
                            if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                              // Instruction LDRSB_i
                              return 84;
                            }
                          }
                        break;}
                        case 0x0U: {
                          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                            // Instruction MULL
                            return 29;
                          }
                        break;}
                        default: {
                          // Invalid pattern
                          return 161;
                        }
                      }
                    }
                    else {
                      if (((instr_code & 0x200000U) == 0x200000) && ((instr_code
                      & 0xf0000000U) != 0xf0000000)) {
                        // Instruction RSC_sr
                        return 17;
                      }
                    }
                  }
                  else {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction SBC_sr
                      return 11;
                    }
                  }
                }
                else {
                  if (((instr_code & 0x200000U) == 0x200000) && ((instr_code &
                  0xf0000000U) != 0xf0000000) && ((instr_code & 0x10f000U) !=
                  0x10f000)) {
                    // Instruction RSC_r
                    return 16;
                  }
                }
              }
              else {
                if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
                0x10f000U) != 0x10f000)) {
                  // Instruction SBC_r
                  return 10;
                }
              }
            break;}
            default: {
              // Invalid pattern
              return 161;
            }
          }
        break;}
        default: {
          // Invalid pattern
          return 161;
        }
      }
    break;}
    case 0x2000000U: {
      switch(instr_code & 0x1800000U) {
        case 0x1000000U: {
          switch(instr_code & 0x300000U) {
            case 0x100000U: {
              if ((instr_code & 0x400000U) != 0x0) {
                if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                  // Instruction CMP_i
                  return 75;
                }
              }
              else {
                if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                  // Instruction TST_i
                  return 49;
                }
              }
            break;}
            case 0x200000U: {
              if ((instr_code & 0x4f0000U) == 0x0) {
                if ((instr_code & 0x10U) == 0x0) {
                  if ((instr_code & 0x7U) != 0x0) {
                    if ((instr_code & 0x1U) == 0x0) {
                      if ((instr_code & 0x2U) == 0x0) {
                        if (((instr_code & 0xecU) == 0x4) && ((instr_code &
                        0xf0000000U) != 0xf0000000)) {
                          // Instruction SEV
                          return 146;
                        }
                      }
                      else {
                        if (((instr_code & 0xecU) == 0x0) && ((instr_code &
                        0xf0000000U) != 0xf0000000)) {
                          // Instruction WFE
                          return 150;
                        }
                      }
                    }
                    else {
                      if ((instr_code & 0x2U) == 0x0) {
                        if (((instr_code & 0xecU) == 0x0) && ((instr_code &
                        0xf0000000U) != 0xf0000000)) {
                          // Instruction YIELD
                          return 152;
                        }
                      }
                      else {
                        if (((instr_code & 0xecU) == 0x0) && ((instr_code &
                        0xf0000000U) != 0xf0000000)) {
                          // Instruction WFI
                          return 151;
                        }
                      }
                    }
                  }
                  else {
                    if (((instr_code & 0xe8U) == 0x0) && ((instr_code & 0xf0000000U)
                    != 0xf0000000)) {
                      // Instruction NOP
                      return 139;
                    }
                  }
                }
                else {
                  if (((instr_code & 0xe0U) == 0xe0) && ((instr_code & 0xf0000000U)
                  != 0xf0000000)) {
                    // Instruction DBG
                    return 135;
                  }
                }
              }
              else {
                if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
                0x4f0000U) != 0x0)) {
                  // Instruction MSR_i
                  return 124;
                }
              }
            break;}
            case 0x300000U: {
              if ((instr_code & 0x400000U) != 0x0) {
                if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                  // Instruction CMN_i
                  return 72;
                }
              }
              else {
                if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                  // Instruction TEQ_i
                  return 46;
                }
              }
            break;}
            case 0x0U: {
              if ((instr_code & 0x400000U) == 0x0) {
                if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                  // Instruction MOVW
                  return 120;
                }
              }
              else {
                if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                  // Instruction MOVT
                  return 121;
                }
              }
            break;}
            default: {
              // Invalid pattern
              return 161;
            }
          }
        break;}
        case 0x1800000U: {
          if ((instr_code & 0x200000U) != 0x0) {
            if ((instr_code & 0x400000U) == 0x0) {
              if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
              0x10f000U) != 0x10f000)) {
                // Instruction MOV_i
                return 118;
              }
            }
            else {
              if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
              0x10f000U) != 0x10f000)) {
                // Instruction MVN_i
                return 40;
              }
            }
          }
          else {
            if ((instr_code & 0x400000U) == 0x0) {
              if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
              0x10f000U) != 0x10f000)) {
                // Instruction ORR_i
                return 43;
              }
            }
            else {
              if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
              0x10f000U) != 0x10f000)) {
                // Instruction BIC_i
                return 61;
              }
            }
          }
        break;}
        case 0x0U: {
          if ((instr_code & 0x200000U) == 0x0) {
            if ((instr_code & 0x400000U) == 0x0) {
              if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
              0x10f000U) != 0x10f000)) {
                // Instruction AND_i
                return 34;
              }
            }
            else {
              if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
              0x10f000U) != 0x10f000)) {
                // Instruction SUB_i
                return 6;
              }
            }
          }
          else {
            if ((instr_code & 0x400000U) == 0x0) {
              if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
              0x10f000U) != 0x10f000)) {
                // Instruction EOR_i
                return 37;
              }
            }
            else {
              if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
              0x10f000U) != 0x10f000)) {
                // Instruction RSB_i
                return 12;
              }
            }
          }
        break;}
        case 0x800000U: {
          if ((instr_code & 0x200000U) == 0x0) {
            if ((instr_code & 0x400000U) == 0x0) {
              if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
              0x10f000U) != 0x10f000)) {
                // Instruction ADD_i
                return 0;
              }
            }
            else {
              if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
              0x10f000U) != 0x10f000)) {
                // Instruction SBC_i
                return 9;
              }
            }
          }
          else {
            if ((instr_code & 0x400000U) == 0x0) {
              if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
              0x10f000U) != 0x10f000)) {
                // Instruction ADC_i
                return 3;
              }
            }
            else {
              if (((instr_code & 0xf0000000U) != 0xf0000000) && ((instr_code &
              0x10f000U) != 0x10f000)) {
                // Instruction RSC_i
                return 15;
              }
            }
          }
        break;}
        default: {
          // Invalid pattern
          return 161;
        }
      }
    break;}
    case 0x6000000U: {
      switch(instr_code & 0x3000000U) {
        case 0x2000000U: {
          switch(instr_code & 0x30U) {
            case 0x0U: {
              if ((instr_code & 0xf0000000U) != 0xf0000000) {
                if ((instr_code & 0x100000U) == 0x0) {
                  if ((instr_code & 0x400000U) == 0x0) {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction STR_r
                      return 95;
                    }
                  }
                  else {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction STRB_r
                      return 98;
                    }
                  }
                }
                else {
                  if ((instr_code & 0x400000U) == 0x0) {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction LDR_r
                      return 79;
                    }
                  }
                  else {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction LDRB_r
                      return 82;
                    }
                  }
                }
              }
              else {
                if (((instr_code & 0x700000U) == 0x500000)) {
                  // Instruction PLI_r
                  return 141;
                }
              }
            break;}
            case 0x20U: {
              if ((instr_code & 0xf0000000U) != 0xf0000000) {
                if ((instr_code & 0x100000U) == 0x0) {
                  if ((instr_code & 0x400000U) == 0x0) {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction STR_r
                      return 95;
                    }
                  }
                  else {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction STRB_r
                      return 98;
                    }
                  }
                }
                else {
                  if ((instr_code & 0x400000U) == 0x0) {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction LDR_r
                      return 79;
                    }
                  }
                  else {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction LDRB_r
                      return 82;
                    }
                  }
                }
              }
              else {
                if (((instr_code & 0x700000U) == 0x500000)) {
                  // Instruction PLI_r
                  return 141;
                }
              }
            break;}
            case 0x30U: {
              switch(instr_code & 0xc0U) {
                case 0x0U: {
                  if ((instr_code & 0x800000U) != 0x0) {
                    if ((instr_code & 0x100000U) != 0x0) {
                      if ((instr_code & 0x400000U) == 0x0) {
                        if (((instr_code & 0x200000U) == 0x200000) && ((instr_code
                        & 0xf0000000U) != 0xf0000000)) {
                          // Instruction REV
                          return 67;
                        }
                      }
                      else {
                        if (((instr_code & 0x200000U) == 0x200000) && ((instr_code
                        & 0xf0000000U) != 0xf0000000)) {
                          // Instruction RBIT
                          return 66;
                        }
                      }
                    }
                    else {
                      if (((instr_code & 0x200000U) == 0x200000) && ((instr_code
                      & 0xf0000000U) != 0xf0000000)) {
                        // Instruction USSAT16
                        return 25;
                      }
                    }
                  }
                  else {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction USHQASX
                      return 22;
                    }
                  }
                break;}
                case 0x80U: {
                  if ((instr_code & 0x100000U) != 0x0) {
                    if ((instr_code & 0x400000U) != 0x0) {
                      if (((instr_code & 0xa00000U) == 0xa00000) && ((instr_code
                      & 0xf0000000U) != 0xf0000000)) {
                        // Instruction REVSH
                        return 69;
                      }
                    }
                    else {
                      if (((instr_code & 0xa00000U) == 0xa00000) && ((instr_code
                      & 0xf0000000U) != 0xf0000000)) {
                        // Instruction REV16
                        return 68;
                      }
                    }
                  }
                  else {
                    if (((instr_code & 0xe00000U) == 0x800000) && ((instr_code &
                    0xf0000000U) != 0xf0000000)) {
                      // Instruction SEL
                      return 71;
                    }
                  }
                break;}
                case 0x40U: {
                  if ((instr_code & 0x800000U) != 0x0) {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction USXTAHB
                      return 21;
                    }
                  }
                  else {
                    if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                      // Instruction USHQSUB
                      return 19;
                    }
                  }
                break;}
                case 0xc0U: {
                  if (((instr_code & 0x800000U) == 0x0) && ((instr_code &
                  0xf0000000U) != 0xf0000000)) {
                    // Instruction USHQSUB
                    return 19;
                  }
                break;}
                default: {
                  // Invalid pattern
                  return 161;
                }
              }
            break;}
            case 0x10U: {
              if ((instr_code & 0x800000U) != 0x0) {
                if ((instr_code & 0x200000U) == 0x0) {
                  if (((instr_code & 0x500000U) == 0x0) && ((instr_code &
                  0xf0000000U) != 0xf0000000)) {
                    // Instruction PKH
                    return 65;
                  }
                }
                else {
                  if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                    // Instruction USSAT
                    return 24;
                  }
                }
              }
              else {
                if ((instr_code & 0x40U) != 0x0) {
                  if (((instr_code & 0x80U) == 0x0) && ((instr_code & 0xf0000000U)
                  != 0xf0000000)) {
                    // Instruction USHQSAX
                    return 23;
                  }
                }
                else {
                  if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                    // Instruction USHQADD
                    return 18;
                  }
                }
              }
            break;}
            default: {
              // Invalid pattern
              return 161;
            }
          }
        break;}
        case 0x3000000U: {
          if ((instr_code & 0xf0000000U) != 0xf0000000) {
            if ((instr_code & 0x400010U) != 0x0) {
              if ((instr_code & 0x100010U) != 0x0) {
                if ((instr_code & 0x10U) != 0x0) {
                  if ((instr_code & 0x800020U) != 0x800020) {
                    if ((instr_code & 0x900000U) != 0x100000) {
                      if ((instr_code & 0xa00000U) != 0x800000) {
                        if ((instr_code & 0x200000U) == 0x0) {
                          if (((instr_code & 0x900000U) == 0x0) && ((instr_code
                          & 0xf0000000U) != 0xf0000000) && ((instr_code & 0xc0U)
                          != 0x80) && ((instr_code & 0xc0U) != 0xc0)) {
                            // Instruction SMMULD
                            return 32;
                          }
                        }
                        else {
                          if (((instr_code & 0x800060U) == 0x800040) && ((instr_code
                          & 0xf0000000U) != 0xf0000000)) {
                            // Instruction USBFX
                            return 70;
                          }
                        }
                      }
                      else {
                        if ((instr_code & 0x400000U) != 0x0) {
                          if (((instr_code & 0x60U) == 0x0) && ((instr_code &
                          0xf0000000U) != 0xf0000000)) {
                            // Instruction BFCI
                            return 60;
                          }
                        }
                        else {
                          if (((instr_code & 0x1000e0U) == 0x0) && ((instr_code
                          & 0xf0000000U) != 0xf0000000)) {
                            // Instruction USADA8
                            return 20;
                          }
                        }
                      }
                    }
                    else {
                      if ((instr_code & 0x400000U) != 0x0) {
                        if (((instr_code & 0x200000U) == 0x0) && ((instr_code &
                        0xf0000000U) != 0xf0000000) && ((instr_code & 0xc0U) !=
                        0x40) && ((instr_code & 0xc0U) != 0x80)) {
                          // Instruction SMMUL
                          return 28;
                        }
                      }
                      else {
                        if (((instr_code & 0xe0U) == 0x0) && ((instr_code &
                        0xf0000000U) != 0xf0000000)) {
                          // Instruction DIV
                          return 33;
                        }
                      }
                    }
                  }
                  else {
                    if (((instr_code & 0xf07000c0U) == 0xe07000c0)) {
                      // Instruction UDF
                      return 149;
                    }
                  }
                }
                else {
                  if (((instr_code & 0x500000U) == 0x500000) && ((instr_code &
                  0xf0000000U) != 0xf0000000)) {
                    // Instruction LDRB_r
                    return 82;
                  }
                }
              }
              else {
                if (((instr_code & 0x400000U) == 0x400000) && ((instr_code &
                0xf0000000U) != 0xf0000000)) {
                  // Instruction STRB_r
                  return 98;
                }
              }
            }
            else {
              if ((instr_code & 0x100000U) == 0x0) {
                if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                  // Instruction STR_r
                  return 95;
                }
              }
              else {
                if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                  // Instruction LDR_r
                  return 79;
                }
              }
            }
          }
          else {
            if (((instr_code & 0x300010U) == 0x100000)) {
              // Instruction PLD_r
              return 143;
            }
          }
        break;}
        default: {
          // Invalid pattern
          return 161;
        }
      }
    break;}
    case 0x8000000U: {
      if ((instr_code & 0xf0000000U) != 0xf0000000) {
        switch(instr_code & 0x1800000U) {
          case 0x800000U: {
            if ((instr_code & 0x100000U) == 0x0) {
              if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                // Instruction STM
                return 112;
              }
            }
            else {
              if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                if (((instr_code & 0xfff0000U) == 0x8bd0000) && ((instr_code &
                0xf0000000U) != 0xf0000000U) && ((instr_code & 0xffffU) != 0x0U)
                && ((instr_code & 0xffffU) != 0x1U) && ((instr_code & 0xffffU)
                != 0x2U) && ((instr_code & 0xffffU) != 0x4U) && ((instr_code &
                0xffffU) != 0x8U) && ((instr_code & 0xffffU) != 0x10U) &&
                ((instr_code & 0xffffU) != 0x20U) && ((instr_code & 0xffffU) !=
                0x40U) && ((instr_code & 0xffffU) != 0x80U) && ((instr_code &
                0xffffU) != 0x100U) && ((instr_code & 0xffffU) != 0x200U) &&
                ((instr_code & 0xffffU) != 0x400U) && ((instr_code & 0xffffU) !=
                0x800U) && ((instr_code & 0xffffU) != 0x1000U) && ((instr_code &
                0xffffU) != 0x2000U) && ((instr_code & 0xffffU) != 0x4000U) &&
                ((instr_code & 0xffffU) != 0x8000U)) {
                  // Instruction POP_block
                  return 111;
                }
                if ((instr_code & 0xf900000U) == 0x8900000U) {
                  // Instruction LDM
                  return 106;
                }
              }
            }
          break;}
          case 0x0U: {
            if ((instr_code & 0x100000U) != 0x0) {
              if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                // Instruction LDMDA
                return 108;
              }
            }
            else {
              if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                // Instruction STMDA
                return 114;
              }
            }
          break;}
          case 0x1000000U: {
            if ((instr_code & 0x100000U) == 0x0) {
              if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                if (((instr_code & 0xfff0000U) == 0x92d0000) && ((instr_code &
                0xf0000000U) != 0xf0000000U) && ((instr_code & 0xffffU) != 0x0U)
                && ((instr_code & 0xffffU) != 0x1U) && ((instr_code & 0xffffU)
                != 0x2U) && ((instr_code & 0xffffU) != 0x4U) && ((instr_code &
                0xffffU) != 0x8U) && ((instr_code & 0xffffU) != 0x10U) &&
                ((instr_code & 0xffffU) != 0x20U) && ((instr_code & 0xffffU) !=
                0x40U) && ((instr_code & 0xffffU) != 0x80U) && ((instr_code &
                0xffffU) != 0x100U) && ((instr_code & 0xffffU) != 0x200U) &&
                ((instr_code & 0xffffU) != 0x400U) && ((instr_code & 0xffffU) !=
                0x800U) && ((instr_code & 0xffffU) != 0x1000U) && ((instr_code &
                0xffffU) != 0x2000U) && ((instr_code & 0xffffU) != 0x4000U) &&
                ((instr_code & 0xffffU) != 0x8000U)) {
                  // Instruction PUSH_block
                  return 117;
                }
                if ((instr_code & 0xf900000U) == 0x9000000U) {
                  // Instruction STMDB
                  return 115;
                }
              }
            }
            else {
              if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                // Instruction LDMDB
                return 109;
              }
            }
          break;}
          case 0x1800000U: {
            if ((instr_code & 0x100000U) == 0x0) {
              if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                // Instruction STMIB
                return 113;
              }
            }
            else {
              if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                // Instruction LDMIB
                return 107;
              }
            }
          break;}
          default: {
            // Invalid pattern
            return 161;
          }
        }
      }
      else {
        if ((instr_code & 0x100000U) != 0x0) {
          if (((instr_code & 0x400000U) == 0x0)) {
            // Instruction RFE
            return 144;
          }
        }
        else {
          if (((instr_code & 0x400000U) == 0x400000)) {
            // Instruction SRS
            return 147;
          }
        }
      }
    break;}
    case 0x4000000U: {
      if ((instr_code & 0x500000U) != 0x0) {
        if ((instr_code & 0x100000U) != 0x0) {
          if ((instr_code & 0xf0000000U) != 0xf0000000) {
            if ((instr_code & 0x400000U) == 0x0) {
              if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                if (((instr_code & 0xfff0fffU) == 0x49d0004) && ((instr_code &
                0xf0000000U) != 0xf0000000U)) {
                  // Instruction POP_single
                  return 110;
                }
                if ((instr_code & 0xe500000U) == 0x4100000U) {
                  // Instruction LDR_i
                  return 78;
                }
              }
            }
            else {
              if (((instr_code & 0xf0000000U) != 0xf0000000)) {
                // Instruction LDRB_i
                return 81;
              }
            }
          }
          else {
            if ((instr_code & 0x200000U) != 0x0) {
              if ((instr_code & 0x10U) != 0x0) {
                if ((instr_code & 0x40U) != 0x0) {
                  if (((instr_code & 0x1c000a0U) == 0x1400000)) {
                    // Instruction DMB
                    return 136;
                  }
                }
                else {
                  if (((instr_code & 0x1c000a0U) == 0x1400000)) {
                    // Instruction CLREX
                    return 133;
                  }
                }
              }
              else {
                if ((instr_code & 0x20U) != 0x0) {
                  if (((instr_code & 0x1c000c0U) == 0x1400040)) {
                    // Instruction ISB
                    return 138;
                  }
                }
                else {
                  if (((instr_code & 0x1c000c0U) == 0x1400040)) {
                    // Instruction DSB
                    return 137;
                  }
                }
              }
            }
            else {
              if ((instr_code & 0x1000000U) == 0x0) {
                if (((instr_code & 0x400000U) == 0x400000)) {
                  // Instruction PLI_i
                  return 140;
                }
              }
              else {
                // Instruction PLD_i
                return 142;
              }
            }
          }
        }
        else {
          if (((instr_code & 0x400000U) == 0x400000) && ((instr_code & 0xf0000000U)
          != 0xf0000000)) {
            // Instruction STRB_i
            return 97;
          }
        }
      }
      else {
        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
          if (((instr_code & 0xfff0fffU) == 0x52d0004) && ((instr_code & 0xf0000000U)
          != 0xf0000000U)) {
            // Instruction PUSH_single
            return 116;
          }
          if ((instr_code & 0xe500000U) == 0x4000000U) {
            // Instruction STR_i
            return 94;
          }
        }
      }
    break;}
    case 0xa000000U: {
      if ((instr_code & 0xf0000000U) != 0xf0000000) {
        if ((instr_code & 0x1000000U) != 0x0) {
          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
            // Instruction BL
            return 127;
          }
        }
        else {
          if (((instr_code & 0xf0000000U) != 0xf0000000)) {
            // Instruction B
            return 126;
          }
        }
      }
      else {
        // Instruction BLX_i
        return 129;
      }
    break;}
    case 0xe000000U: {
      if ((instr_code & 0x1000000U) != 0x0) {
        if (((instr_code & 0xf0000000U) != 0xf0000000)) {
          // Instruction SVC
          return 148;
        }
      }
      else {
        if ((instr_code & 0x10U) != 0x0) {
          if ((instr_code & 0x100000U) != 0x0) {
            if (((instr_code & 0xf00U) != 0xa00) && ((instr_code & 0xf00U) !=
            0xb00)) {
              // Instruction MRC
              return 159;
            }
          }
          else {
            if (((instr_code & 0xf00U) != 0xa00) && ((instr_code & 0xf00U) !=
            0xb00)) {
              // Instruction MCR
              return 157;
            }
          }
        }
        else {
          if (((instr_code & 0xf00U) != 0xa00) && ((instr_code & 0xf00U) !=
          0xb00)) {
            // Instruction CDP
            return 154;
          }
        }
      }
    break;}
    case 0xc000000U: {
      if ((instr_code & 0x100000U) != 0x0) {
        if ((instr_code & 0x1a00000U) != 0x0) {
          if (((instr_code & 0x1a00000U) != 0x0) && ((instr_code & 0xf00U) !=
          0xa00) && ((instr_code & 0xf00U) != 0xb00)) {
            // Instruction LDC
            return 155;
          }
        }
        else {
          if (((instr_code & 0x400000U) == 0x400000) && ((instr_code & 0xf00U)
          != 0xa00) && ((instr_code & 0xf00U) != 0xb00)) {
            // Instruction MRRC
            return 160;
          }
        }
      }
      else {
        if ((instr_code & 0x1a00000U) == 0x0) {
          if (((instr_code & 0x400000U) == 0x400000) && ((instr_code & 0xf00U)
          != 0xa00) && ((instr_code & 0xf00U) != 0xb00)) {
            // Instruction MCRR
            return 158;
          }
        }
        else {
          if (((instr_code & 0x1a00000U) != 0x0) && ((instr_code & 0xf00U) !=
          0xa00) && ((instr_code & 0xf00U) != 0xb00)) {
            // Instruction STC
            return 156;
          }
        }
      }
    break;}
    default: {
      // Invalid pattern
      return 161;
    }
  }
  // Invalid pattern
  return 161;
} // decode()

// -----------------------------------------------------------------------------


// *****************************************************************************

