/***************************************************************************//**
*
*           _/       _/_/_/      _/         _/
*         _/_/      _/    _/    _/_/      __/
*       _/  _/     _/    _/    _/ _/    _/_/
*     _/_/_/_/    _/_/_/      _/  _/  _/ _/
*   _/      _/   _/    _/    _/   _/_/  _/
* _/        _/  _/      _/  _/    _/   _/
*
* @brief    This file is part of the SoCRocket ARM ISS generated by TRAP.
* @details  This SystemC model was automatically generated by running
*           $ python ARMArch.py
*           Please refer to the ARM TRAP source files for documentation.
* @author   Lillian Tadros (Technische Universitaet Dortmund)
* @date     2015-2016 Technische Universitaet Dortmund
*
*
* (c) 2014-2016
* Technische Universitaet Dortmund
* Institut fuer Roboterforschung
* Project Embedded Multi-Core Systems for Mixed Criticality
* Applications in Dynamic and Changeable Real-time Environments (EMC2)
*
*
* This file is part of ARMCortexA9.
*
* ARMCortexA9 is free software; you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation; either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
* or see <http://www.gnu.org/licenses/>.
*
*******************************************************************************/

#ifndef CORE_ARMCORTEXA9_FUNC_LT_IRQPORTS_HPP
#define CORE_ARMCORTEXA9_FUNC_LT_IRQPORTS_HPP


#include <systemc.h>
#include <tlm.h>
#include <common/report.hpp>
#include <tlm_utils/multi_passthrough_target_socket.h>


#define FUNC_MODEL
#define LT_IF

namespace core_armcortexa9_funclt {

  class TLMIntrPort_1 : public sc_module {
    /// @name Constructors and Destructors
    /// @{

    public:
    TLMIntrPort_1(sc_module_name port_name, bool& irq_signal);

    /// @} Constructors and Destructors
    // -------------------------------------------------------------------------
    /// @name Methods
    /// @{

    public:
    void b_transport(
        int tag, tlm::tlm_generic_payload& trans, sc_time& delay);
    unsigned transport_dbg(int tag, tlm::tlm_generic_payload& trans);
    tlm::tlm_sync_enum nb_transport_fw(
        int tag, tlm::tlm_generic_payload& trans, tlm::tlm_phase& phase, sc_time&
        delay);

    /// @} Methods
    // -------------------------------------------------------------------------
    /// @name Data
    /// @{

    public:
    bool& irq_signal;
    tlm_utils::multi_passthrough_target_socket<TLMIntrPort_1, 1, tlm::tlm_base_protocol_types,
    1, sc_core::SC_ZERO_OR_MORE_BOUND> target_socket;

    /// @} Data
    // -------------------------------------------------------------------------

  }; // class TLMIntrPort_1

  // ***************************************************************************

} // namespace core_armcortexa9_funclt

#endif // CORE_ARMCORTEXA9_FUNC_LT_IRQPORTS_HPP
