/***************************************************************************//**
*
*           _/       _/_/_/      _/         _/
*         _/_/      _/    _/    _/_/      __/
*       _/  _/     _/    _/    _/ _/    _/_/
*     _/_/_/_/    _/_/_/      _/  _/  _/ _/
*   _/      _/   _/    _/    _/   _/_/  _/
* _/        _/  _/      _/  _/    _/   _/
*
* @brief    This file is part of the SoCRocket ARM ISS generated by TRAP.
* @details  This SystemC model was automatically generated by running
*           $ python ARMArch.py
*           Please refer to the ARM TRAP source files for documentation.
* @author   Lillian Tadros (Technische Universitaet Dortmund)
* @date     2015-2016 Technische Universitaet Dortmund
*
*
* (c) 2014-2016
* Technische Universitaet Dortmund
* Institut fuer Roboterforschung
* Project Embedded Multi-Core Systems for Mixed Criticality
* Applications in Dynamic and Changeable Real-time Environments (EMC2)
*
*
* This file is part of ARMCortexA9.
*
* ARMCortexA9 is free software; you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation; either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
* or see <http://www.gnu.org/licenses/>.
*
*******************************************************************************/

#ifndef CORE_ARMCORTEXA9_FUNC_LT_PROCESSOR_HPP
#define CORE_ARMCORTEXA9_FUNC_LT_PROCESSOR_HPP

#include "memory.hpp"
#include "instructions.hpp"
#include "interface.hpp"
#include "registers.hpp"
#include "irqPorts.hpp"
#include "decoder.hpp"

#include <systemc.h>
#include <tlm_utils/tlm_quantumkeeper.h>
#include <common/report.hpp>
#include <string>
#include <common/tools_if.hpp>
#include <boost/circular_buffer.hpp>
#include <modules/instruction.hpp>
#include <iostream>
#include <fstream>

#ifdef __GNUC__
#ifdef __GNUC_MINOR__
#if (__GNUC__ >= 4 && __GNUC_MINOR__ >= 3)
#include <tr1/unordered_map>
#define template_map std::tr1::unordered_map
#else
#include <ext/hash_map>
#define  template_map __gnu_cxx::hash_map
#endif
#else
#include <ext/hash_map>
#define  template_map __gnu_cxx::hash_map
#endif
#else
#ifdef _WIN32
#include <hash_map>
#define  template_map stdext::hash_map
#else
#include <map>
#define  template_map std::map
#endif
#endif

#define FUNC_MODEL
#define LT_IF

using namespace trap;

namespace core_armcortexa9_funclt {

  /**
  * @brief Processor Class
  *
  * The top-level processor class holding the pipeline, registers and ports.
  */
  class CoreARMCortexA9FuncLT : public sc_module {
    /// @name Constructors and Destructors
    /// @{

    public:
    CoreARMCortexA9FuncLT(
    sc_module_name name, MemoryInterface* mem, bool extensions_vfp = true, bool extensions_simd = true, bool extensions_cp
    = true, bool extensions_virtualization = true, bool extensions_security =
    true, bool extensions_large_physical_address = false, bool extensions_mp =
    true, bool extensions_debug = false, bool ismode_arm = true, bool ismode_thumb
    = false, bool ismode_jazelle = false, bool ismode_thumbee = false);
    ~CoreARMCortexA9FuncLT();

    /// @} Constructors and Destructors
    // -------------------------------------------------------------------------
    /// @name Methods
    /// @{

    public:
    void main_loop();
    void reset();
    void end_of_elaboration();
    void enable_history(std::string file_name = "");
    Instruction* decode(unsigned bitstring);
    Interface& get_interface();

    /// @} Methods
    // -------------------------------------------------------------------------
    /// @name Data
    /// @{

    public:
    SC_HAS_PROCESS(CoreARMCortexA9FuncLT);unsigned total_cycles;
    tlm_utils::tlm_quantumkeeper quantKeeper;
    Registers R;
    MemoryInterface& instr_memory;
    MemoryInterface& data_memory;
    //TLMIntrPort_1 IRQ_port;
    //TLMIntrPort_1 FIQ_port;
    unsigned num_instructions;
    IRQIntrInstruction* IRQ_instr;
    FIQIntrInstruction* FIQ_instr;
    ToolsManager<unsigned> tool_manager;
    boost::circular_buffer<HistoryInstrType> history_instr_queue;
    unsigned history_undumped_elements;
    unsigned ENTRY_POINT;
    unsigned MPROC_ID;
    unsigned PROGRAM_LIMIT;
    unsigned PROGRAM_START;
    Interface* ABIIf;

    private:
    static int num_instances;
    bool reset_called;
    bool IRQ;
    bool FIQ;
    Instruction** INSTRUCTIONS;
    bool instr_executing;
    template_map<unsigned, CacheElem> instr_cache;
    bool history_en;
    std::ofstream history_file;
    bool extensions_vfp;
    bool extensions_simd;
    bool extensions_cp;
    bool extensions_virtualization;
    bool extensions_security;
    bool extensions_large_physical_address;
    bool extensions_mp;
    bool extensions_debug;
    bool ismode_arm;
    bool ismode_thumb;
    bool ismode_jazelle;
    bool ismode_thumbee;
    Decoder decoder;

    /// @} Data
    // -------------------------------------------------------------------------

  }; // class CoreARMCortexA9FuncLT

  // ***************************************************************************

} // namespace core_armcortexa9_funclt

#endif // CORE_ARMCORTEXA9_FUNC_LT_PROCESSOR_HPP
