/***************************************************************************//**
*
*           _/       _/_/_/      _/         _/
*         _/_/      _/    _/    _/_/      __/
*       _/  _/     _/    _/    _/ _/    _/_/
*     _/_/_/_/    _/_/_/      _/  _/  _/ _/
*   _/      _/   _/    _/    _/   _/_/  _/
* _/        _/  _/      _/  _/    _/   _/
*
* @brief    This file is part of the SoCRocket ARM ISS generated by TRAP.
* @details  This SystemC model was automatically generated by running
*           $ python ARMArch.py
*           Please refer to the ARM TRAP source files for documentation.
* @author   Lillian Tadros (TUDO ETIT IRF)
* @date     2014-12-01 tadros: Initial ARM Cortex A9 (ARMv7-A) version
*
*
* (c) 2014-2016
* Technische Universitaet Dortmund
* Institut fuer Roboterforschung
* Project Embedded Multi-Core Systems for Mixed Criticality
* Applications in Dynamic and Changeable Real-time Environments (EMC2)
*
*
* This file is part of ARMCortexA9.
*
* ARMCortexA9 is free software; you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation; either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
* or see <http://www.gnu.org/licenses/>.
*
*******************************************************************************/

#ifndef CORE_ARMCORTEXA9_FUNC_LT_PROCESSOR_HPP
#define CORE_ARMCORTEXA9_FUNC_LT_PROCESSOR_HPP

#include "arm/intunit/instructions.hpp"
#include "arm/intunit/interface.hpp"
#include "arm/intunit/registers.hpp"
#include "arm/intunit/memory.hpp"
#include "arm/intunit/irqPorts.hpp"
#include "arm/intunit/decoder.hpp"

#include <systemc.h>
#include <common/report.hpp>
#include <string>
#include <common/tools_if.hpp>
#include <tlm_utils/tlm_quantumkeeper.h>
#include <boost/circular_buffer.hpp>
#include <modules/instruction.hpp>
#include <iostream>
#include <fstream>

#ifdef __GNUC__
#ifdef __GNUC_MINOR__
#if (__GNUC__ >= 4 && __GNUC_MINOR__ >= 3)
#include <tr1/unordered_map>
#define template_map std::tr1::unordered_map
#else
#include <ext/hash_map>
#define  template_map __gnu_cxx::hash_map
#endif
#else
#include <ext/hash_map>
#define  template_map __gnu_cxx::hash_map
#endif
#else
#ifdef _WIN32
#include <hash_map>
#define  template_map stdext::hash_map
#else
#include <map>
#define  template_map std::map
#endif
#endif


#define FUNC_MODEL
#define LT_IF


using namespace trap;

namespace core_armcortexa9_lt {

  /**
  * @brief Processor Class
  *
  * The top-level processor class holding the pipeline, registers and ports.
  */
  class CoreARMCortexA9LT : public sc_module {
    /// @name Constructors and Destructors
    /// @{

    public:
    SC_HAS_PROCESS(CoreARMCortexA9LT);
    CoreARMCortexA9LT(
        sc_module_name name, MemoryInterface *memory, bool _extensions_vfp = true, bool _extensions_simd
        = true, bool _extensions_cp = true, bool _extensions_virtualization =
        true, bool _extensions_security = true, bool _extensions_large_physical_address = false,
        bool _extensions_mp = true, bool _extensions_debug = false, bool _ismode_arm = true,
        bool _ismode_thumb = false, bool _ismode_jazelle = false, bool _ismode_thumbee
        = false);
    ~CoreARMCortexA9LT();

    /// @} Constructors and Destructors
    /// ------------------------------------------------------------------------
    /// @name Methods
    /// @{

    public:
    void main_loop();
    void reset();
    void end_of_elaboration();
    tlm_utils::tlm_quantumkeeper quantKeeper;
    Instruction* decode(unsigned bitstring);
    Interface& get_interface();
    void enable_history(std::string file_name = "");

    /// @} Methods
    /// ------------------------------------------------------------------------
    /// @name Data
    /// @{

    public:
    Interface* ABIIf;
    ToolsManager<unsigned> tool_manager;
    Registers R;
    MemoryInterface *mem;
    MemoryInterface &data_memory;
    unsigned total_cycles;
    boost::circular_buffer<HistoryInstrType> history_instr_queue;
    unsigned history_undumped_elements;
    unsigned num_instructions;
    unsigned ENTRY_POINT;
    unsigned MPROC_ID;
    unsigned PROGRAM_LIMIT;
    unsigned PROGRAM_START;
    TLMIntrPort_1 IRQ_port;
    TLMIntrPort_1 FIQ_port;
    IRQIntrInstruction* IRQ_instr;
    FIQIntrInstruction* FIQ_instr;

    private:
    bool reset_called;
    Decoder decoder;
    bool extensions_vfp;
    bool extensions_simd;
    bool extensions_cp;
    bool extensions_virtualization;
    bool extensions_security;
    bool extensions_large_physical_address;
    bool extensions_mp;
    bool extensions_debug;
    bool ismode_arm;
    bool ismode_thumb;
    bool ismode_jazelle;
    bool ismode_thumbee;
    std::ofstream history_file;
    bool history_en;
    bool instr_executing;
    Instruction** INSTRUCTIONS;
    template_map<unsigned, CacheElem> instr_cache;
    static int num_instances;
    bool IRQ;
    bool FIQ;

    /// @} Data
    /// ------------------------------------------------------------------------

  }; // class CoreARMCortexA9LT

  /// **************************************************************************

} // namespace core_armcortexa9_lt

#endif // CORE_ARMCORTEXA9_FUNC_LT_PROCESSOR_HPP
