/***************************************************************************//**
*
*           _/       _/_/_/      _/         _/
*         _/_/      _/    _/    _/_/      __/
*       _/  _/     _/    _/    _/ _/    _/_/
*     _/_/_/_/    _/_/_/      _/  _/  _/ _/
*   _/      _/   _/    _/    _/   _/_/  _/
* _/        _/  _/      _/  _/    _/   _/
*
* @brief    This file is part of the SoCRocket ARM ISS generated by TRAP.
* @details  This SystemC model was automatically generated by running
*           $ python ARMArch.py
*           Please refer to the ARM TRAP source files for documentation.
* @author   Lillian Tadros (Technische Universitaet Dortmund)
* @date     2015-2016 Technische Universitaet Dortmund
*
*
* (c) 2014-2016
* Technische Universitaet Dortmund
* Institut fuer Roboterforschung
* Project Embedded Multi-Core Systems for Mixed Criticality
* Applications in Dynamic and Changeable Real-time Environments (EMC2)
*
*
* This file is part of ARMCortexA9.
*
* ARMCortexA9 is free software; you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation; either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
* or see <http://www.gnu.org/licenses/>.
*
*******************************************************************************/

#ifndef CORE_ARMCORTEXA9_FUNC_LT_REGISTERS_HPP
#define CORE_ARMCORTEXA9_FUNC_LT_REGISTERS_HPP


#include <iostream>
#include <modules/register.hpp>


#define FUNC_MODEL
#define LT_IF

/// Instruction Set States: ARM, Thumb, Jazelle, ThumbEE
enum class ISMODE: unsigned {
  ARM,        // 0x0
  THUMB,      // 0x1
  JAZELLE,    // 0x2
  THUMBEE     // 0x3
};

/// Execution States/Privilege Levels:
/// PL0: USR
/// PL1: SYS, IRQ, FIQ, UND, ABT, SVC, MON (only in Secure State)
/// PL2: HYP (only in Non-secure State and Virtualization Extensions)
enum class EXECMODE: unsigned {
  USR = 0x10,
  FIQ = 0x11,
  IRQ = 0x12,
  SVC = 0x13,
  MON = 0x16,
  ABT = 0x17,
  HYP = 0x1A,
  UND = 0x1B,
  SYS = 0x1F
};

#define CPSR R.cpsr
#define SCR R.scr
#define SCTLR R.sctlr
#define MP_ID R.mp_id
#define SPSR R.spsr
#define RB R.rb
#define CPREGS R.cpregs
#define SPSR_IRQ R.spsr_irq
#define SPSR_FIQ R.spsr_fiq
#define SPSR_UND R.spsr_und
#define SPSR_ABT R.spsr_abt
#define SPSR_SVC R.spsr_svc
#define SPSR_HYP R.spsr_hyp
#define SPSR_MON R.spsr_mon
#define SP_IRQ R.sp_irq
#define LR_IRQ R.lr_irq
#define R8_FIQ R.r8_fiq
#define R9_FIQ R.r9_fiq
#define R10_FIQ R.r10_fiq
#define R11_FIQ R.r11_fiq
#define R12_FIQ R.r12_fiq
#define SP_FIQ R.sp_fiq
#define LR_FIQ R.lr_fiq
#define SP_UND R.sp_und
#define LR_UND R.lr_und
#define SP_ABT R.sp_abt
#define LR_ABT R.lr_abt
#define SP_SVC R.sp_svc
#define LR_SVC R.lr_svc
#define SP_HYP R.sp_hyp
#define ELR_HYP R.elr_hyp
#define SP_MON R.sp_mon
#define LR_MON R.lr_mon
#define SP R.sp
#define LR R.lr
#define PC R.pc
#define REGS R.regs

enum FIELDS_CPSR {
  CPSR_N,
  CPSR_Z,
  CPSR_C,
  CPSR_V,
  CPSR_Q,
  CPSR_IT10,
  CPSR_J,
  CPSR_GE,
  CPSR_IT72,
  CPSR_E,
  CPSR_A,
  CPSR_I,
  CPSR_F,
  CPSR_T,
  CPSR_M
}; // enum FIELDS_CPSR

enum FIELDS_SCR {
  SCR_UNK_SBZP,
  SCR_SIF,
  SCR_HCE,
  SCR_SCD,
  SCR_nET,
  SCR_AW,
  SCR_FW,
  SCR_EA,
  SCR_FIQ,
  SCR_IRQ,
  SCR_NS
}; // enum FIELDS_SCR

enum FIELDS_SCTLR {
  SCTLR_B31,
  SCTLR_TE,
  SCTLR_AFE,
  SCTLR_TRE,
  SCTLR_NMFI,
  SCTLR_B26,
  SCTLR_EE,
  SCTLR_VE,
  SCTLR_B2223,
  SCTLR_FI,
  SCTLR_UWXN,
  SCTLR_WXN,
  SCTLR_B18,
  SCTLR_HA,
  SCTLR_B1516,
  SCTLR_RR,
  SCTLR_V,
  SCTLR_I,
  SCTLR_Z,
  SCTLR_SW,
  SCTLR_B69,
  SCTLR_CP15BEN,
  SCTLR_B34,
  SCTLR_C,
  SCTLR_A,
  SCTLR_M
}; // enum FIELDS_SCTLR

enum FIELDS_SPSR {
  SPSR_N,
  SPSR_Z,
  SPSR_C,
  SPSR_V,
  SPSR_Q,
  SPSR_IT10,
  SPSR_J,
  SPSR_GE,
  SPSR_IT72,
  SPSR_E,
  SPSR_A,
  SPSR_I,
  SPSR_F,
  SPSR_T,
  SPSR_M
}; // enum FIELDS_SPSR

namespace core_armcortexa9_funclt {

  /**
  * @brief Register Container Class
  *
  * Contains all registers and register banks of the processor as member variables.
  * It serves for encapsulating the instantiation details (defining fields, etc)
  * away from the processor. It also simplifies passing the registers to the
  * instructions, instead of passing each register individually.
  */
  class Registers {
    /// @name Constructors and Destructors
    /// @{

    public:
    Registers(unsigned MPROC_ID, unsigned ENTRY_POINT);

    /// @} Constructors and Destructors
    // -------------------------------------------------------------------------
    /// @name Methods
    /// @{

    public:
    void reset();
    bool write(const unsigned& data);
    bool write_dbg(const unsigned& data);
    bool write_force(const unsigned& data);
    void execute_callbacks(
        const scireg_ns::scireg_callback_type& type, const uint32_t& offset = 0,
        const uint32_t& size = 0);
    void set_stage(unsigned stage);
    void unset_stage();
    void clock_cycle();
    void stall(unsigned stage);
    void advance();
    void flush(unsigned stage);
    std::ostream& operator <<(std::ostream& os) const;

    /// @} Methods
    // -------------------------------------------------------------------------
    /// @name Data
    /// @{

    public:
    trap::Register<unsigned> cpsr;
    trap::Register<unsigned> scr;
    trap::Register<unsigned> sctlr;
    trap::Register<unsigned> mp_id;
    trap::Register<unsigned> spsr[7];
    trap::Register<unsigned> rb[35];
    trap::Register<unsigned> cpregs[16];
    trap::RegisterAlias<unsigned> spsr_irq;
    trap::RegisterAlias<unsigned> spsr_fiq;
    trap::RegisterAlias<unsigned> spsr_und;
    trap::RegisterAlias<unsigned> spsr_abt;
    trap::RegisterAlias<unsigned> spsr_svc;
    trap::RegisterAlias<unsigned> spsr_hyp;
    trap::RegisterAlias<unsigned> spsr_mon;
    trap::RegisterAlias<unsigned> sp_irq;
    trap::RegisterAlias<unsigned> lr_irq;
    trap::RegisterAlias<unsigned> r8_fiq;
    trap::RegisterAlias<unsigned> r9_fiq;
    trap::RegisterAlias<unsigned> r10_fiq;
    trap::RegisterAlias<unsigned> r11_fiq;
    trap::RegisterAlias<unsigned> r12_fiq;
    trap::RegisterAlias<unsigned> sp_fiq;
    trap::RegisterAlias<unsigned> lr_fiq;
    trap::RegisterAlias<unsigned> sp_und;
    trap::RegisterAlias<unsigned> lr_und;
    trap::RegisterAlias<unsigned> sp_abt;
    trap::RegisterAlias<unsigned> lr_abt;
    trap::RegisterAlias<unsigned> sp_svc;
    trap::RegisterAlias<unsigned> lr_svc;
    trap::RegisterAlias<unsigned> sp_hyp;
    trap::RegisterAlias<unsigned> elr_hyp;
    trap::RegisterAlias<unsigned> sp_mon;
    trap::RegisterAlias<unsigned> lr_mon;
    trap::RegisterAlias<unsigned> sp;
    trap::RegisterAlias<unsigned> lr;
    trap::RegisterAlias<unsigned> pc;
    trap::RegisterAlias<unsigned> regs[16];

    /// @} Data
    // -------------------------------------------------------------------------

  }; // class Registers

  // ***************************************************************************

} // namespace core_armcortexa9_funclt

#endif // CORE_ARMCORTEXA9_FUNC_LT_REGISTERS_HPP
