/***************************************************************************//**
*
*           _/       _/_/_/      _/         _/
*         _/_/      _/    _/    _/_/      __/
*       _/  _/     _/    _/    _/ _/    _/_/
*     _/_/_/_/    _/_/_/      _/  _/  _/ _/
*   _/      _/   _/    _/    _/   _/_/  _/
* _/        _/  _/      _/  _/    _/   _/
*
* @brief    This file is part of the SoCRocket ARM ISS generated by TRAP.
* @details  This SystemC model was automatically generated by running
*           $ python ARMArch.py
*           Please refer to the ARM TRAP source files for documentation.
* @author   Lillian Tadros (TUDO ETIT IRF)
* @date     2014-12-01 tadros: Initial ARM Cortex A9 (ARMv7-A) version
*
*
* (c) 2014-2016
* Technische Universitaet Dortmund
* Institut fuer Roboterforschung
* Project Embedded Multi-Core Systems for Mixed Criticality
* Applications in Dynamic and Changeable Real-time Environments (EMC2)
*
*
* This file is part of ARMCortexA9.
*
* ARMCortexA9 is free software; you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation; either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
* or see <http://www.gnu.org/licenses/>.
*
*******************************************************************************/

#include "arm/intunit/registers.hpp"

#include <iostream>
#include <modules/register.hpp>


using namespace core_armcortexa9_lt;

core_armcortexa9_lt::Registers::Registers(
    unsigned MPROC_ID,
    unsigned ENTRY_POINT) :
  cpsr("cpsr", trap::amba_LT, 8, false, 0, 0, 0xd3),
  id_pfr0("id_pfr0", trap::amba_LT, 8, false, 0, 0, 0x1),
  id_pfr1("id_pfr1", trap::amba_LT, 8, false, 0, 0, 0x1011),
  id_dfr0("id_dfr0", trap::amba_LT, 8, false, 0, 0, 0x0),
  id_afr0("id_afr0", trap::amba_LT, 8, false, 0, 3, 0x1111),
  id_mmfr0("id_mmfr0", trap::amba_LT, 8, false, 0, 0, 0x0),
  id_mmfr1("id_mmfr1", trap::amba_LT, 8, false, 0, 0, 0x0),
  id_mmfr2("id_mmfr2", trap::amba_LT, 8, false, 0, 0, 0x0),
  id_mmfr3("id_mmfr3", trap::amba_LT, 8, false, 0, 0, 0x0),
  id_isar0("id_isar0", trap::amba_LT, 8, false, 0, 0, 0x0),
  id_isar1("id_isar1", trap::amba_LT, 8, false, 0, 0, 0x0),
  id_isar2("id_isar2", trap::amba_LT, 8, false, 0, 0, 0x0),
  id_isar3("id_isar3", trap::amba_LT, 8, false, 0, 0, 0x0),
  id_isar4("id_isar4", trap::amba_LT, 8, false, 0, 0, 0x0),
  id_isar5("id_isar5", trap::amba_LT, 8, false, 0, 0, 0x0),
  mp_id("mp_id", trap::amba_LT, 8, false, 0, 0, MPROC_ID),
  spsr {{"spsr[0]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"spsr[1]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"spsr[2]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"spsr[3]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"spsr[4]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"spsr[5]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"spsr[6]", trap::amba_LT, 8, false, 0, 0, 0x0}},
  rb {{"rb[0]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[1]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[2]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[3]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[4]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[5]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[6]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[7]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[8]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[9]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[10]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[11]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[12]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[13]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[14]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[15]", trap::amba_LT, 8, false, 0, 0, ENTRY_POINT},
  {"rb[16]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[17]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[18]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[19]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[20]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[21]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[22]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[23]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[24]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[25]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[26]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[27]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[28]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[29]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[30]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[31]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[32]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[33]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"rb[34]", trap::amba_LT, 8, false, 0, 0, 0x0}},
  cpregs {{"cpregs[0]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"cpregs[1]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"cpregs[2]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"cpregs[3]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"cpregs[4]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"cpregs[5]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"cpregs[6]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"cpregs[7]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"cpregs[8]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"cpregs[9]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"cpregs[10]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"cpregs[11]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"cpregs[12]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"cpregs[13]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"cpregs[14]", trap::amba_LT, 8, false, 0, 0, 0x0},
  {"cpregs[15]", trap::amba_LT, 8, false, 0, 0, 0x0}},
  spsr_irq("spsr_irq"),
  spsr_fiq("spsr_fiq"),
  spsr_und("spsr_und"),
  spsr_abt("spsr_abt"),
  spsr_svc("spsr_svc"),
  spsr_hyp("spsr_hyp"),
  spsr_mon("spsr_mon"),
  sp("sp"),
  lr("lr"),
  pc("pc"),
  sp_irq("sp_irq"),
  lr_irq("lr_irq"),
  r8_fiq("r8_fiq"),
  r9_fiq("r9_fiq"),
  r10_fiq("r10_fiq"),
  r11_fiq("r11_fiq"),
  r12_fiq("r12_fiq"),
  sp_fiq("sp_fiq"),
  lr_fiq("lr_fiq"),
  sp_und("sp_und"),
  lr_und("lr_und"),
  sp_abt("sp_abt"),
  lr_abt("lr_abt"),
  sp_svc("sp_svc"),
  lr_svc("lr_svc"),
  sp_hyp("sp_hyp"),
  elr_hyp("elr_hyp"),
  sp_mon("sp_mon"),
  lr_mon("lr_mon"),
  regs {{"regs[0]"},{"regs[1]"},{"regs[2]"},{"regs[3]"},{"regs[4]"},{"regs[5]"},
  {"regs[6]"},{"regs[7]"},{"regs[8]"},{"regs[9]"},{"regs[10]"},{"regs[11]"},
  {"regs[12]"},{"regs[13]"},{"regs[14]"},{"regs[15]"}} {
  // Initialize registers.
  cpsr.add_field("A", 8, 8);
  cpsr.add_field("C", 29, 29);
  cpsr.add_field("E", 9, 9);
  cpsr.add_field("F", 6, 6);
  cpsr.add_field("I", 7, 7);
  cpsr.add_field("J", 24, 24);
  cpsr.add_field("M", 4, 0);
  cpsr.add_field("N", 31, 31);
  cpsr.add_field("Q", 27, 27);
  cpsr.add_field("GE", 19, 16);
  cpsr.add_field("T", 5, 5);
  cpsr.add_field("V", 28, 28);
  cpsr.add_field("Z", 30, 30);
  cpsr.add_field("IT10", 26, 25);
  cpsr.add_field("IT72", 15, 10);

  id_pfr0.add_field("W7", 31, 28);
  id_pfr0.add_field("W6", 27, 24);
  id_pfr0.add_field("W5", 23, 20);
  id_pfr0.add_field("W4", 19, 16);
  id_pfr0.add_field("W3", 15, 12);
  id_pfr0.add_field("W2", 11, 8);
  id_pfr0.add_field("W1", 7, 4);
  id_pfr0.add_field("W0", 3, 0);

  id_pfr1.add_field("W7", 31, 28);
  id_pfr1.add_field("W6", 27, 24);
  id_pfr1.add_field("W5", 23, 20);
  id_pfr1.add_field("W4", 19, 16);
  id_pfr1.add_field("W3", 15, 12);
  id_pfr1.add_field("W2", 11, 8);
  id_pfr1.add_field("W1", 7, 4);
  id_pfr1.add_field("W0", 3, 0);

  id_dfr0.add_field("W7", 31, 28);
  id_dfr0.add_field("W6", 27, 24);
  id_dfr0.add_field("W5", 23, 20);
  id_dfr0.add_field("W4", 19, 16);
  id_dfr0.add_field("W3", 15, 12);
  id_dfr0.add_field("W2", 11, 8);
  id_dfr0.add_field("W1", 7, 4);
  id_dfr0.add_field("W0", 3, 0);

  id_afr0.add_field("W7", 31, 28);
  id_afr0.add_field("W6", 27, 24);
  id_afr0.add_field("W5", 23, 20);
  id_afr0.add_field("W4", 19, 16);
  id_afr0.add_field("W3", 15, 12);
  id_afr0.add_field("W2", 11, 8);
  id_afr0.add_field("W1", 7, 4);
  id_afr0.add_field("W0", 3, 0);

  id_mmfr0.add_field("W7", 31, 28);
  id_mmfr0.add_field("W6", 27, 24);
  id_mmfr0.add_field("W5", 23, 20);
  id_mmfr0.add_field("W4", 19, 16);
  id_mmfr0.add_field("W3", 15, 12);
  id_mmfr0.add_field("W2", 11, 8);
  id_mmfr0.add_field("W1", 7, 4);
  id_mmfr0.add_field("W0", 3, 0);

  id_mmfr1.add_field("W7", 31, 28);
  id_mmfr1.add_field("W6", 27, 24);
  id_mmfr1.add_field("W5", 23, 20);
  id_mmfr1.add_field("W4", 19, 16);
  id_mmfr1.add_field("W3", 15, 12);
  id_mmfr1.add_field("W2", 11, 8);
  id_mmfr1.add_field("W1", 7, 4);
  id_mmfr1.add_field("W0", 3, 0);

  id_mmfr2.add_field("W7", 31, 28);
  id_mmfr2.add_field("W6", 27, 24);
  id_mmfr2.add_field("W5", 23, 20);
  id_mmfr2.add_field("W4", 19, 16);
  id_mmfr2.add_field("W3", 15, 12);
  id_mmfr2.add_field("W2", 11, 8);
  id_mmfr2.add_field("W1", 7, 4);
  id_mmfr2.add_field("W0", 3, 0);

  id_mmfr3.add_field("W7", 31, 28);
  id_mmfr3.add_field("W6", 27, 24);
  id_mmfr3.add_field("W5", 23, 20);
  id_mmfr3.add_field("W4", 19, 16);
  id_mmfr3.add_field("W3", 15, 12);
  id_mmfr3.add_field("W2", 11, 8);
  id_mmfr3.add_field("W1", 7, 4);
  id_mmfr3.add_field("W0", 3, 0);

  id_isar0.add_field("W7", 31, 28);
  id_isar0.add_field("W6", 27, 24);
  id_isar0.add_field("W5", 23, 20);
  id_isar0.add_field("W4", 19, 16);
  id_isar0.add_field("W3", 15, 12);
  id_isar0.add_field("W2", 11, 8);
  id_isar0.add_field("W1", 7, 4);
  id_isar0.add_field("W0", 3, 0);

  id_isar1.add_field("W7", 31, 28);
  id_isar1.add_field("W6", 27, 24);
  id_isar1.add_field("W5", 23, 20);
  id_isar1.add_field("W4", 19, 16);
  id_isar1.add_field("W3", 15, 12);
  id_isar1.add_field("W2", 11, 8);
  id_isar1.add_field("W1", 7, 4);
  id_isar1.add_field("W0", 3, 0);

  id_isar2.add_field("W7", 31, 28);
  id_isar2.add_field("W6", 27, 24);
  id_isar2.add_field("W5", 23, 20);
  id_isar2.add_field("W4", 19, 16);
  id_isar2.add_field("W3", 15, 12);
  id_isar2.add_field("W2", 11, 8);
  id_isar2.add_field("W1", 7, 4);
  id_isar2.add_field("W0", 3, 0);

  id_isar3.add_field("W7", 31, 28);
  id_isar3.add_field("W6", 27, 24);
  id_isar3.add_field("W5", 23, 20);
  id_isar3.add_field("W4", 19, 16);
  id_isar3.add_field("W3", 15, 12);
  id_isar3.add_field("W2", 11, 8);
  id_isar3.add_field("W1", 7, 4);
  id_isar3.add_field("W0", 3, 0);

  id_isar4.add_field("W7", 31, 28);
  id_isar4.add_field("W6", 27, 24);
  id_isar4.add_field("W5", 23, 20);
  id_isar4.add_field("W4", 19, 16);
  id_isar4.add_field("W3", 15, 12);
  id_isar4.add_field("W2", 11, 8);
  id_isar4.add_field("W1", 7, 4);
  id_isar4.add_field("W0", 3, 0);

  id_isar5.add_field("W7", 31, 28);
  id_isar5.add_field("W6", 27, 24);
  id_isar5.add_field("W5", 23, 20);
  id_isar5.add_field("W4", 19, 16);
  id_isar5.add_field("W3", 15, 12);
  id_isar5.add_field("W2", 11, 8);
  id_isar5.add_field("W1", 7, 4);
  id_isar5.add_field("W0", 3, 0);

  // Initialize register banks.
  for (unsigned i = 0; i < 7; ++i) {
    spsr[i].add_field("A", 8, 8);
    spsr[i].add_field("C", 29, 29);
    spsr[i].add_field("E", 9, 9);
    spsr[i].add_field("F", 6, 6);
    spsr[i].add_field("I", 7, 7);
    spsr[i].add_field("J", 24, 24);
    spsr[i].add_field("M", 4, 0);
    spsr[i].add_field("N", 31, 31);
    spsr[i].add_field("Q", 27, 27);
    spsr[i].add_field("GE", 19, 16);
    spsr[i].add_field("T", 5, 5);
    spsr[i].add_field("V", 28, 28);
    spsr[i].add_field("Z", 30, 30);
    spsr[i].add_field("IT10", 26, 25);
    spsr[i].add_field("IT72", 15, 10);
  }

  // Initialize alias registers and alias register banks.
  this->lr_mon.update_alias(this->rb[34], 0);
  this->sp_mon.update_alias(this->rb[33], 0);
  this->elr_hyp.update_alias(this->rb[32], 0);
  this->sp_hyp.update_alias(this->rb[31], 0);
  this->lr_svc.update_alias(this->rb[30], 0);
  this->sp_svc.update_alias(this->rb[29], 0);
  this->lr_abt.update_alias(this->rb[28], 0);
  this->sp_abt.update_alias(this->rb[27], 0);
  this->lr_und.update_alias(this->rb[26], 0);
  this->sp_und.update_alias(this->rb[25], 0);
  this->lr_fiq.update_alias(this->rb[24], 0);
  this->sp_fiq.update_alias(this->rb[23], 0);
  this->r12_fiq.update_alias(this->rb[22], 0);
  this->spsr_mon.update_alias(this->spsr[6], 0);
  this->r11_fiq.update_alias(this->rb[21], 0);
  this->spsr_hyp.update_alias(this->spsr[5], 0);
  this->r10_fiq.update_alias(this->rb[20], 0);
  this->spsr_svc.update_alias(this->spsr[4], 0);
  this->r9_fiq.update_alias(this->rb[19], 0);
  this->spsr_abt.update_alias(this->spsr[3], 0);
  this->r8_fiq.update_alias(this->rb[18], 0);
  this->spsr_und.update_alias(this->spsr[2], 0);
  this->lr_irq.update_alias(this->rb[17], 0);
  this->spsr_fiq.update_alias(this->spsr[1], 0);
  this->sp_irq.update_alias(this->rb[16], 0);
  this->spsr_irq.update_alias(this->spsr[0], 0);
  this->regs[0].update_alias(this->rb[0], 0);
  this->regs[1].update_alias(this->rb[1], 0);
  this->regs[2].update_alias(this->rb[2], 0);
  this->regs[3].update_alias(this->rb[3], 0);
  this->regs[4].update_alias(this->rb[4], 0);
  this->regs[5].update_alias(this->rb[5], 0);
  this->regs[6].update_alias(this->rb[6], 0);
  this->regs[7].update_alias(this->rb[7], 0);
  this->regs[8].update_alias(this->rb[8], 0);
  this->regs[9].update_alias(this->rb[9], 0);
  this->regs[10].update_alias(this->rb[10], 0);
  this->regs[11].update_alias(this->rb[11], 0);
  this->regs[12].update_alias(this->rb[12], 0);
  this->regs[13].update_alias(this->rb[13], 0);
  this->regs[14].update_alias(this->rb[14], 0);
  this->regs[15].update_alias(this->rb[15], 4);
  this->sp.update_alias(this->regs[13], 0);
  this->pc.update_alias(this->regs[15], 0);
  this->lr.update_alias(this->regs[14], 0);
} // Registers()

/// ----------------------------------------------------------------------------

void core_armcortexa9_lt::Registers::reset() {
  // Reset registers.
  cpsr.reset();
  id_pfr0.reset();
  id_pfr1.reset();
  id_dfr0.reset();
  id_afr0.reset();
  id_mmfr0.reset();
  id_mmfr1.reset();
  id_mmfr2.reset();
  id_mmfr3.reset();
  id_isar0.reset();
  id_isar1.reset();
  id_isar2.reset();
  id_isar3.reset();
  id_isar4.reset();
  id_isar5.reset();
  mp_id.reset();

  // Reset register banks.
  for (int i = 0; i < 7; ++i) {
    spsr[i].reset();
  }

  for (int i = 0; i < 35; ++i) {
    rb[i].reset();
  }

  for (int i = 0; i < 16; ++i) {
    cpregs[i].reset();
  }
} // reset()

/// ----------------------------------------------------------------------------

bool core_armcortexa9_lt::Registers::write(const unsigned& data) {
  bool ret = true;

  // Write registers.
  ret = ret && cpsr.write(data);
  ret = ret && id_pfr0.write(data);
  ret = ret && id_pfr1.write(data);
  ret = ret && id_dfr0.write(data);
  ret = ret && id_afr0.write(data);
  ret = ret && id_mmfr0.write(data);
  ret = ret && id_mmfr1.write(data);
  ret = ret && id_mmfr2.write(data);
  ret = ret && id_mmfr3.write(data);
  ret = ret && id_isar0.write(data);
  ret = ret && id_isar1.write(data);
  ret = ret && id_isar2.write(data);
  ret = ret && id_isar3.write(data);
  ret = ret && id_isar4.write(data);
  ret = ret && id_isar5.write(data);
  ret = ret && mp_id.write(data);

  // Write register banks.
  for (int i = 0; i < 7; ++i) {
    ret = ret && spsr[i].write(data);
  }

  for (int i = 0; i < 35; ++i) {
    ret = ret && rb[i].write(data);
  }

  for (int i = 0; i < 16; ++i) {
    ret = ret && cpregs[i].write(data);
  }

  return ret;
} // write()

/// ----------------------------------------------------------------------------

bool core_armcortexa9_lt::Registers::write_dbg(const unsigned& data) {
  bool ret = true;

  // Write registers.
  ret = ret && cpsr.write_dbg(data);
  ret = ret && id_pfr0.write_dbg(data);
  ret = ret && id_pfr1.write_dbg(data);
  ret = ret && id_dfr0.write_dbg(data);
  ret = ret && id_afr0.write_dbg(data);
  ret = ret && id_mmfr0.write_dbg(data);
  ret = ret && id_mmfr1.write_dbg(data);
  ret = ret && id_mmfr2.write_dbg(data);
  ret = ret && id_mmfr3.write_dbg(data);
  ret = ret && id_isar0.write_dbg(data);
  ret = ret && id_isar1.write_dbg(data);
  ret = ret && id_isar2.write_dbg(data);
  ret = ret && id_isar3.write_dbg(data);
  ret = ret && id_isar4.write_dbg(data);
  ret = ret && id_isar5.write_dbg(data);
  ret = ret && mp_id.write_dbg(data);

  // Write register banks.
  for (int i = 0; i < 7; ++i) {
    ret = ret && spsr[i].write_dbg(data);
  }

  for (int i = 0; i < 35; ++i) {
    ret = ret && rb[i].write_dbg(data);
  }

  for (int i = 0; i < 16; ++i) {
    ret = ret && cpregs[i].write_dbg(data);
  }

  return ret;
} // write_dbg()

/// ----------------------------------------------------------------------------

bool core_armcortexa9_lt::Registers::write_force(const unsigned& data) {
  bool ret = true;

  // Write registers.
  ret = ret && cpsr.write_force(data);
  ret = ret && id_pfr0.write_force(data);
  ret = ret && id_pfr1.write_force(data);
  ret = ret && id_dfr0.write_force(data);
  ret = ret && id_afr0.write_force(data);
  ret = ret && id_mmfr0.write_force(data);
  ret = ret && id_mmfr1.write_force(data);
  ret = ret && id_mmfr2.write_force(data);
  ret = ret && id_mmfr3.write_force(data);
  ret = ret && id_isar0.write_force(data);
  ret = ret && id_isar1.write_force(data);
  ret = ret && id_isar2.write_force(data);
  ret = ret && id_isar3.write_force(data);
  ret = ret && id_isar4.write_force(data);
  ret = ret && id_isar5.write_force(data);
  ret = ret && mp_id.write_force(data);

  // Write register banks.
  for (int i = 0; i < 7; ++i) {
    ret = ret && spsr[i].write_force(data);
  }

  for (int i = 0; i < 35; ++i) {
    ret = ret && rb[i].write_force(data);
  }

  for (int i = 0; i < 16; ++i) {
    ret = ret && cpregs[i].write_force(data);
  }

  return ret;
} // write_force()

/// ----------------------------------------------------------------------------

void core_armcortexa9_lt::Registers::execute_callbacks(
    const scireg_ns::scireg_callback_type& type,
    const uint32_t& offset,
    const uint32_t& size) {
  // Execute callbacks on registers.
  cpsr.execute_callbacks(type, 0, sizeof(unsigned));
  id_pfr0.execute_callbacks(type, 0, sizeof(unsigned));
  id_pfr1.execute_callbacks(type, 0, sizeof(unsigned));
  id_dfr0.execute_callbacks(type, 0, sizeof(unsigned));
  id_afr0.execute_callbacks(type, 0, sizeof(unsigned));
  id_mmfr0.execute_callbacks(type, 0, sizeof(unsigned));
  id_mmfr1.execute_callbacks(type, 0, sizeof(unsigned));
  id_mmfr2.execute_callbacks(type, 0, sizeof(unsigned));
  id_mmfr3.execute_callbacks(type, 0, sizeof(unsigned));
  id_isar0.execute_callbacks(type, 0, sizeof(unsigned));
  id_isar1.execute_callbacks(type, 0, sizeof(unsigned));
  id_isar2.execute_callbacks(type, 0, sizeof(unsigned));
  id_isar3.execute_callbacks(type, 0, sizeof(unsigned));
  id_isar4.execute_callbacks(type, 0, sizeof(unsigned));
  id_isar5.execute_callbacks(type, 0, sizeof(unsigned));
  mp_id.execute_callbacks(type, 0, sizeof(unsigned));

  // Execute callbacks on register banks.
  for (int i = 0; i < 7; ++i) {
    spsr[i].execute_callbacks(type, 0, sizeof(unsigned));
  }

  for (int i = 0; i < 35; ++i) {
    rb[i].execute_callbacks(type, 0, sizeof(unsigned));
  }

  for (int i = 0; i < 16; ++i) {
    cpregs[i].execute_callbacks(type, 0, sizeof(unsigned));
  }
} // execute_callbacks()

/// ----------------------------------------------------------------------------

std::ostream& core_armcortexa9_lt::Registers::operator <<(std::ostream& os)
const {
  os << std::hex << std::showbase;

  // Print registers.
  os << cpsr.name() << ": " << cpsr.read_dbg() << '\n';
  os << id_pfr0.name() << ": " << id_pfr0.read_dbg() << '\n';
  os << id_pfr1.name() << ": " << id_pfr1.read_dbg() << '\n';
  os << id_dfr0.name() << ": " << id_dfr0.read_dbg() << '\n';
  os << id_afr0.name() << ": " << id_afr0.read_dbg() << '\n';
  os << id_mmfr0.name() << ": " << id_mmfr0.read_dbg() << '\n';
  os << id_mmfr1.name() << ": " << id_mmfr1.read_dbg() << '\n';
  os << id_mmfr2.name() << ": " << id_mmfr2.read_dbg() << '\n';
  os << id_mmfr3.name() << ": " << id_mmfr3.read_dbg() << '\n';
  os << id_isar0.name() << ": " << id_isar0.read_dbg() << '\n';
  os << id_isar1.name() << ": " << id_isar1.read_dbg() << '\n';
  os << id_isar2.name() << ": " << id_isar2.read_dbg() << '\n';
  os << id_isar3.name() << ": " << id_isar3.read_dbg() << '\n';
  os << id_isar4.name() << ": " << id_isar4.read_dbg() << '\n';
  os << id_isar5.name() << ": " << id_isar5.read_dbg() << '\n';
  os << mp_id.name() << ": " << mp_id.read_dbg() << '\n';

  // Print register banks.
  for (int i = 0; i < 7; ++i) {
    os << spsr[i].name() << ": " << spsr[i].read_dbg() << '\n';
  }

  for (int i = 0; i < 35; ++i) {
    os << rb[i].name() << ": " << rb[i].read_dbg() << '\n';
  }

  for (int i = 0; i < 16; ++i) {
    os << cpregs[i].name() << ": " << cpregs[i].read_dbg() << '\n';
  }

  os << std::dec;
  return os;
} // Registers::operator <<()

/// ----------------------------------------------------------------------------


/// ****************************************************************************

