#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os


def build(bld):
    bld.recurse('tests')

    sources = """
        instructions.cpp
        registers.cpp
        processor.cpp
        interface.cpp
        decoder.cpp
        memory.cpp
        irqPorts.cpp
    """
    uselib = 'BOOST SYSTEMC TLM TRAP'
    objects = ''
    includes = '.'
    target = 'funcLT_objs'

    bld.objects(source = sources, target = target, use = uselib + ' ' + objects, includes = includes)
    sources = 'main.cpp'
    includes = '.'
    uselib = 'TRAP BOOST ELF_LIB SYSTEMC TLM AMBA'
    import sys
    cppflags_custom = ''
    if sys.platform == 'cygwin':
        cppflags_custom = ' -D__USE_W32_SOCKETS'
        uselib += ' WINSOCK'
    objects = 'funcLT_objs'
    target = 'funcLT'

    bld.program(source = sources, target = target, use = uselib + ' ' + objects, includes = includes, defines = cppflags_custom)
