/*******************************************************************************
*
*
*
*
*
* This file is part of MICROBLAZE.
*
* MICROBLAZE is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the
* Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
* or see <http://www.gnu.org/licenses/>.
*
*******************************************************************************/


#include "microblaze/intunit/main.hpp"
#include "microblaze/intunit/decoderTests.hpp"
#include "microblaze/intunit/isaTests0.hpp"
#include "microblaze/intunit/isaTests1.hpp"
#include "microblaze/intunit/isaTests2.hpp"
#include "microblaze/intunit/isaTests3.hpp"


#include <boost/test/included/unit_test.hpp>
#include <systemc.h>


void trap_log_formatter::log_entry_value(
    std::ostream & output,
    ::boost::unit_test::const_string value) {
  output << std::showbase << std::hex << value;
} // log_entry_value()

boost::unit_test::test_suite * init_unit_test_suite(
    int argc,
    char * argv[]) {
  trap_log_formatter* trap_log_formatter_ptr = new trap_log_formatter;
  boost::unit_test::unit_test_log.set_formatter(trap_log_formatter_ptr);
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADD_0_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_1_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDK_2_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDKC_3_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDI_4_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIC_5_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIK_6_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIKC_7_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&AND_8_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ANDI_9_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ANDN_10_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ANDNI_11_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BEQ_12_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BEQD_13_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BEQI_14_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BEQID_15_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGE_16_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGED_17_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGEI_18_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGEID_19_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGT_20_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGTD_21_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGTI_22_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGTID_23_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLE_24_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLED_25_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLEI_26_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLEID_27_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLT_28_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLTD_29_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLTI_30_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLTID_31_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BNE_32_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BNED_33_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BNEI_34_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BNEID_35_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BR_36_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRA_37_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRD_38_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRAD_39_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRLD_40_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRALD_41_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRI_42_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRAI_43_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRID_44_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRAID_45_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRLID_46_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRALID_47_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRK_48_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRKI_49_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSRL_50_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSRA_51_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSLL_52_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSRLI_53_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSRAI_54_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSLLI_55_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMP_56_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMPU_57_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&FADD_58_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&FRSUB_59_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&FMUL_60_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&FDIV_61_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&FCMP_62_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&FLT_63_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&FINT_64_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&FSQRT_65_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&IDIV_66_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&IDIVU_67_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&IMM_68_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LBU_69_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LBUI_70_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LHU_71_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LHUI_72_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LW_73_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LWI_74_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MFS_75_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MSRCLR_76_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MSRSET_77_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MTS_78_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MUL_79_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULH_80_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULHU_81_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULHSU_82_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULI_83_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&OR_84_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ORI_85_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&PCMPBF_86_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&PCMPEQ_87_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&PCMPNE_88_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUB_89_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBC_90_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBK_91_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBKC_92_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBI_93_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIC_94_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIK_95_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIKC_96_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTBD_97_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTID_98_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTED_99_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTSD_100_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SB_101_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SBI_102_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SH_103_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SHI_104_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SW_105_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SWI_106_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SEXT16_107_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SEXT8_108_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRA_109_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRC_110_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRL_111_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&WDC_112_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&WIC_113_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&XOR_114_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&XORI_115_decode));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGE_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGE_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGE_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGEID_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGEID_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSLL_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSLL_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSLL_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGT_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGT_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGT_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BR_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BNED_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BNED_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BNEI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BNEI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BNEI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LBU_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LBU_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LBU_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUB_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUB_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUB_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUB_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUB_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSRLI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSRLI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&FDIV_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&FADD_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULHU_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULHU_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULHU_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULHU_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGTD_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGTD_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGTI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGTI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGTI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SEXT8_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SEXT8_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SEXT8_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LHU_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LHU_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LHU_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LHU_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LHU_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BNE_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BNE_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BNE_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRLD_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRKI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRKI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRKI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRKI_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRKI_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIKC_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIKC_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIKC_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIKC_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIKC_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&IDIV_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&IDIV_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&IDIV_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_6));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_7));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_8));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_9));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_10));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_11));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_12));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_13));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDC_14));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LBUI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LBUI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LBUI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDK_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDK_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDK_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDK_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDK_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDK_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDK_6));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDK_7));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&OR_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&OR_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDI_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDI_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDI_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BEQID_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BEQID_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMPU_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMPU_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMPU_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMPU_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMPU_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMPU_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMPU_6));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMPU_7));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMPU_8));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSRL_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSRL_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSRL_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLTI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLTI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLTI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&PCMPEQ_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&PCMPEQ_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&XOR_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&XOR_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&XOR_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BEQ_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BEQ_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BEQ_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLTD_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLTD_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMP_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMP_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMP_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMP_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMP_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMP_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMP_6));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&CMP_7));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRALID_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTBD_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTBD_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTBD_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MFS_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MFS_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLT_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLT_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLT_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRLID_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SB_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SB_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SB_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLE_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLE_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLE_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SHI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SHI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SHI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SHI_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SHI_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&AND_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&AND_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&AND_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIC_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIC_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIC_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIC_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIC_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIC_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SBI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SBI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SBI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTED_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTED_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTED_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTED_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIK_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIK_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIK_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIK_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIK_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIK_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRALD_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRA_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SEXT16_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SEXT16_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SEXT16_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SWI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SWI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SWI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SWI_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SWI_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLEID_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLEID_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSRA_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSRA_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSRA_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLED_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLED_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULI_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULI_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MSRSET_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MSRSET_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MSRSET_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MUL_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MUL_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MUL_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MUL_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MUL_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MUL_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MUL_6));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLEI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLEI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLEI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ANDN_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ANDI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ANDI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDKC_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDKC_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDKC_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDKC_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDKC_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDKC_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDKC_6));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDKC_7));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MSRCLR_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MSRCLR_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MSRCLR_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSLLI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSLLI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGEI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGEI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGEI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRC_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRC_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRC_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRC_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRC_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRC_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRC_6));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRC_7));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRC_8));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRC_9));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRA_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRA_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRA_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRA_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRA_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRA_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&IMM_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&IMM_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRL_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRL_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRL_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRL_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRL_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SRL_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&FLT_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULHSU_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULHSU_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULHSU_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULHSU_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULHSU_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULHSU_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADD_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADD_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADD_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADD_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADD_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADD_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADD_6));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADD_7));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADD_8));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADD_9));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADD_10));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADD_11));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADD_12));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&XORI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&XORI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&XORI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&PCMPNE_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&PCMPNE_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSRAI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BSRAI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRAID_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBKC_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBKC_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBKC_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBKC_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBKC_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SW_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SW_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SW_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SW_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SW_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SH_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SH_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SH_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SH_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&SH_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRK_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRK_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ORI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ORI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ORI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ORI_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ANDNI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRD_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LHUI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LHUI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LHUI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LHUI_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LHUI_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIKC_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIKC_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIKC_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIKC_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIKC_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBIKC_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULH_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULH_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULH_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULH_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULH_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MULH_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&FRSUB_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BEQI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BEQI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BEQI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BEQD_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BEQD_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTID_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTID_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTID_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTID_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RTID_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&FMUL_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LWI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LWI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LWI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LWI_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LWI_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BNEID_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BNEID_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIK_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIK_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIK_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIK_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIK_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGTID_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGTID_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIC_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIC_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIC_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIC_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&ADDIC_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LW_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LW_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LW_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LW_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&LW_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBC_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBC_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBC_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBC_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBC_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLTID_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BLTID_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBI_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBI_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBI_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBI_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBI_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBI_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MTS_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&MTS_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBK_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBK_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBK_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBK_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&RSUBK_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGED_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BGED_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRID_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&PCMPBF_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&PCMPBF_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&PCMPBF_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&PCMPBF_3));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&PCMPBF_4));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&PCMPBF_5));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&IDIVU_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&IDIVU_1));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&IDIVU_2));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRAD_0));
  boost::unit_test::framework::master_test_suite().add(BOOST_TEST_CASE(&BRAI_0));

  return 0;
} // init_unit_test_suite()

/** @brief    Main Processor Component Testbench
*   @details
*   Uses the boost::test framework to call the tests defined in decoderTests
*   and isaTests*. Each test instantiates the required DUT submodules individually.
*/
int sc_main(
    int argc,
    char * * argv) {
  return boost::unit_test::unit_test_main(&init_unit_test_suite, argc, argv);
} // sc_main()


