#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../..'

def build(self):
  self(
    target          = 'emc2commitregister',
    features        = 'cxx cxxstlib',
    source          = 'commitregister.cpp', 
    export_includes   = self.repository_root.abspath(),
    includes          = self.repository_root.abspath(),
    use             = 'common BOOST SYSTEMC TLM AMBA GREENSOCS',
    install_path    = '${PREFIX}/lib',
  )
