#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

def build(bld):
    if bld.env['LICENSE'] == 'gpl':
        elfInclude = '../libbfd'
    else:
        elfInclude = '../libelf'
    
    bld.objects(
        target = 'syscall',
        source = 'syscCallB.cpp',
        includes = '. .. ' + elfInclude,
        use = 'ELF_LIB SYSTEMC BOOST BOOST_REGEX',
        install_path = None
    )
    
    bld.install_files(os.path.join(bld.env.PREFIX, 'include', 'osEmulator'), 'osEmulator.hpp syscCallB.hpp')
