#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../../..'

def build(self):

    self(
        target          = 'microblaze',
        features        = 'cxx cxxstlib',
        export_includes = self.top_dir,
        includes        = self.top_dir,
        use             = 'mmucache trap common',
        source          = [
                            'intunit/instructions.cpp',
                            'intunit/registers.cpp',
                            'intunit/alias.cpp',
                            'intunit/processor.cpp',
                            'intunit/interface.cpp',
                            'intunit/decoder.cpp',
                            #'intunit/irqPorts.cpp',
                            #'intunit/externalPins.cpp',
                            'microblaze.cpp',
                          ],
        install_path    = '${PREFIX}/lib',
        defines         = 'ENABLE_HISTORY', 
    )
