#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os


def build(bld):
    sources = """
        decoderTests.cpp
        isaTests0.cpp
        isaTests1.cpp
        isaTests2.cpp
        isaTests3.cpp
        main.cpp
    """
    uselib = 'TRAP BOOST BOOST_TEST ELF_LIB SYSTEMC TLM'
    objects = 'funcLT_objs'
    includes = '. ..'
    target = 'tests'

    bld.program(source = sources, target = target, use = uselib + ' ' + objects, includes = includes)
