#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

def build(bld):
    bld.objects(
        target = 'utils',
        source = 'trap_utils.cpp',
        includes = '. ..',
        install_path = None
    )

    bld.install_files(os.path.join(bld.env.PREFIX, 'include', 'utils'), 'trap_utils.hpp customExceptions.hpp')
