#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '..'
REPOSITORY_PATH = "arm"
REPOSITORY_NAME = "ARM Extensions"
REPOSITORY_DESC = "SoCRockets ARM extensions"
REPOSITORY_TOOLS = [
]

def build(self):
  self.recurse_all()
  self.recurse_all_tests()
  self(
        target       = 'sr_arm',
        features     = 'cxx cxxshlib',
        cxxflags     = '-std=gnu++11',
        source = [
            'arm/mmucache/icio_payload_extension.cpp',
            'arm/mmucache/dcio_payload_extension.cpp',
            'arm/mmucache/localram.cpp',
            'arm/mmucache/nocache.cpp',
            'arm/mmucache/vectorcache.cpp',
            'arm/mmucache/ivectorcache.cpp',
            'arm/mmucache/dvectorcache.cpp',
            'arm/mmucache/mmu.cpp',
            'arm/mmucache/mmu_cache.cpp',
            'arm/mmucache/mmu_cache_base.cpp',
            'arm/mmucache/defines.cpp',
            'arm/intunit/instructions.cpp',
            'arm/intunit/registers.cpp',
            'arm/intunit/processor.cpp',
            'arm/intunit/interface.cpp',
            'arm/intunit/decoder.cpp',
            'arm/intunit/irqPorts.cpp',
            #'arm/intunit/externalPins.cpp',
            'arm/cortexa9.cpp',
            'gic/gic.cpp'
        ],
        includes = [self.repository_root.abspath()],
        defines = 'ENABLE_HISTORY', 
        use          = [
                        'sr_gaisler',
                        'sr_registry',
                        'sr_register',
                        'sr_report',
                        'sr_signal',
                        'common',
                        'AMBA', 'GREENSOCS', 'TLM', 'SYSTEMC', 'BOOST'
                       ],
        idx=98,
  )
